Phala-Network/phala-blockchain

- pruntime/enclave/Cargo.toml
- pruntime/enclave/Enclave.config.xml
- pruntime/enclave/src/contracts/mod.rs
- pruntime/enclave/src/contracts/web3analytics.rs
- pruntime/enclave/src/contracts/woothee/dataset.rs
- pruntime/enclave/src/contracts/woothee/mod.rs
- pruntime/enclave/src/contracts/woothee/parser.rs
- pruntime/enclave/src/contracts/woothee/woothee.rs
- pruntime/enclave/src/lib.rs
> Web3 Analytics Contract

- pruntime/app/Cargo.toml
- pruntime/app/src/main.rs
- pruntime/app/src/tests.rs
- pruntime/enclave/src/contracts/web3analytics.rs
- pruntime/enclave/src/contracts/woothee/dataset.rs
- pruntime/enclave/src/contracts/woothee/parser.rs
> W3A unit tests & bug fix

- .github/workflows/build.yml
Walkaround for https://github.com/substrate-developer-hub/substrate-contracts-workshop/issues/75
> CI: stick to a working nightly

- phost/src/main.rs
- phost/src/msg_sync.rs
- phost/src/notify_client.rs
- phost/src/types.rs
Add `--notify-endpoint` to PHost, e.g. `--notify-endpoint "http://127.0.0.1:3000"`
If it set, PHost will `POST` the endpoint when reaching some checkpoints
```json
{
"headernum": 1001,
"blocknum": 1001,
"pruntime_initialized": true,
"pruntime_new_init": true,
"initial_sync_finished": false
}
```
> Phost notify url

- Cargo.lock
- pruntime/app/Cargo.lock
- pruntime/app/src/main.rs
- pruntime/enclave/Cargo.lock
- pruntime/enclave/Cargo.toml
- pruntime/enclave/Enclave.edl
- pruntime/enclave/src/lib.rs
- use `http_req` instead of raw socket
- upgrade dependencies
> rewrite RA

- Cargo.lock
- pallets/phala/Cargo.toml
- pallets/phala/src/lib.rs
- pallets/phala/src/migrations_3_1_0.rs
- pallets/phala/src/tests.rs
- pruntime/enclave/Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
- scripts/js/dumpPhalaModuleStates.js
Fixes #119 
Tested:
fork-off-substrate & dumpPhalaModuleStats.js
> Fix #119 online worker stats inconsistency

- scripts/js/topUpControllers.js
> refactor top-up controllers script

- Cargo.lock
- pallets/phala/Cargo.toml
- pallets/phala/src/lib.rs
- pallets/phala/src/tests.rs
- pruntime/enclave/Cargo.lock
- runtime/src/lib.rs
Also add comprehensive negative test cases
> Fix multiple kick offline bug

- scripts/js/findSlash.js
Tested:
on fork from the live chain
> script: findSlash.js

- Cargo.lock
- pallets/phala/Cargo.toml
- pallets/phala/src/lib.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/tests.rs
- pruntime/enclave/Cargo.lock
- runtime/src/lib.rs
> pallet-phala: fix the decimals of the slash amount

- standalone/phost/src/main.rs
- standalone/phost/src/msg_sync.rs
- standalone/phost/src/notify_client.rs
- standalone/pruntime/enclave/src/contracts/web3analytics.rs
change:
1. `str.is_empty()` is more readable than `str != ""`
2. bool type impl Copy Trait, doesn't need to clone
> use is_empty() to check str/vec whether empty

- Cargo.lock
- standalone/phost/Cargo.toml
- standalone/phost/src/chain_client.rs
- standalone/phost/src/error.rs
- standalone/phost/src/main.rs
- standalone/phost/src/msg_sync.rs
- standalone/phost/src/notify_client.rs
- standalone/phost/src/pruntime_client.rs
- standalone/pruntime/enclave/Cargo.lock
- standalone/pruntime/enclave/Cargo.toml
- standalone/pruntime/enclave/src/cert.rs
- standalone/pruntime/enclave/src/contracts/assets.rs
- standalone/pruntime/enclave/src/contracts/balances.rs
- standalone/pruntime/enclave/src/contracts/diem.rs
- standalone/pruntime/enclave/src/contracts/mod.rs
- standalone/pruntime/enclave/src/contracts/web3analytics.rs
- standalone/pruntime/enclave/src/cryptography/ecdh.rs
- standalone/pruntime/enclave/src/cryptography/mod.rs
- standalone/pruntime/enclave/src/lib.rs
- standalone/pruntime/enclave/src/light_validation/justification.rs
- standalone/pruntime/enclave/src/light_validation/mod.rs
- standalone/pruntime/enclave/src/light_validation/storage_proof.rs
- standalone/pruntime/enclave/src/system/comp_election.rs
- standalone/pruntime/enclave/src/system/mod.rs
- standalone/pruntime/enclave/src/types.rs
Fixes #174.
All three core blockchain applications (phala-node, phost and pruntime) builds successfully, but while running phost, the following error message results:
```
Connected to substrate at: ws://localhost:9944
bridge() exited with result: Err(SubxtRpcError(Metadata(ModuleNotFound("Phala"))))
```
I don't understand how this is possible when I have `phala-node` running in the background, and I'm pretty sure it does have the Phala module.
> Use anyhow for error handling in pRuntime and pHost

- scripts/js/transferFromAcala.js
> Script tx from acala

- pallets/phala/src/lib.rs
- pallets/phala/src/tests.rs
- standalone/pruntime/enclave/Cargo.lock
- standalone/pruntime/enclave/src/system/mod.rs
- standalone/runtime/src/lib.rs
- rename WorkerRenewed to WorkerReset
- bump runtime version from 32 to 33
> pallet: reset ingress seq when slash

- README.md
1) pRuntime has been merged, fix mentions and paths
2) Some missing steps (macOS, SGX SDK, WebUI)
> Update README: pRuntime & general fixes

- pallets/bridge_transfer/src/lib.rs
- Split lottery command into two events
- Move transfer_lottery to impl block and add sudo method for test
- Decode command before send to  TEE
> Some updates of lottery module

- Cargo.lock
- pallets/bridge_transfer/src/lib.rs
- pallets/kitties/Cargo.toml
- pallets/kitties/README.md
- pallets/kitties/src/hashing.rs
- pallets/kitties/src/lib.rs
- standalone/node/src/chain_spec.rs
- standalone/phost/src/main.rs
- standalone/phost/src/msg_sync.rs
- standalone/phost/src/runtimes.rs
- standalone/phost/src/types.rs
- standalone/pruntime/enclave/Cargo.lock
- standalone/pruntime/enclave/Cargo.toml
- standalone/pruntime/enclave/src/contracts/btc_lottery.rs
- standalone/pruntime/enclave/src/contracts/mod.rs
- standalone/pruntime/enclave/src/contracts/substrate_kitties.rs
- standalone/pruntime/enclave/src/lib.rs
- standalone/runtime/Cargo.toml
- standalone/runtime/src/lib.rs
> Btc lottery final

- standalone/phost/src/main.rs
Later commits will based on this PR. Please consider merge it in advance.
> phost: cargo fmt main.rs

- crates/trie-storage/src/lib.rs
This fixes the OOM in enclave while synchronizing storage.
> trie-storage: Fix a memory leak

- standalone/pruntime/enclave/src/lib.rs
Saw it by accident. Don't know why it did not break the production.
> enclave: Fix a buffer overflow

- common/types/src/lib.rs
- pallets/phala/src/lib.rs
- pallets/phala/src/mq.rs
- pallets/phala/src/phala_legacy/mock.rs
- pallets/phala/src/phala_legacy/mod.rs
- pallets/phala/src/phala_legacy/tests.rs
- pallets/phala/src/registry.rs
- standalone/pruntime/enclave/src/contracts/btc_lottery.rs
- standalone/runtime/src/lib.rs
(This PR is based on #225, and is designed as the substrate end support for #224,)
> Message queue pallet pallet-mq

- Cargo.lock
- pallets/bridge/src/mock.rs
- pallets/bridge/src/tests.rs
- pallets/bridge_transfer/Cargo.toml
- pallets/bridge_transfer/src/mock.rs
- pallets/bridge_transfer/src/tests.rs
- pallets/phala/src/registry.rs
Fix unit test of pallet bridge and pallet bridge-transfer
> Fix testing

- common/types/src/lib.rs
- crates/phala-mq/Cargo.toml
- crates/phala-mq/src/types.rs
- crates/phala-mq/tests/tests.rs
- pallets/phala/src/lib.rs
- pallets/phala/src/mining.rs
- pallets/phala/src/phala_legacy/mod.rs
- pallets/phala/src/registry.rs
- pallets/phala/src/stakepool.rs
- standalone/pruntime/enclave/Cargo.lock
- standalone/pruntime/enclave/Cargo.toml
- standalone/pruntime/enclave/src/cryptography/ecdh.rs
- standalone/pruntime/enclave/src/lib.rs
- Add pallet-registry, pallet-mining, pallet-stakepool
- Use `sp_core::ecdsa::Public` instead of `[u8; 33]` or `Vec<u8` everywhere
- Remove the use of secp256k1
Tested:
- Local tests
> Mining interface skeleton implementation

- pallets/phala/src/mining.rs
- pallets/phala/src/mq.rs
- standalone/phost/build.rs
- standalone/phost/src/runtimes.rs
- standalone/runtime/src/lib.rs
- subxt/src/events.rs
> Add new mining pallets to runtime

- pallets/bridge/src/lib.rs
- pallets/bridge/src/mock.rs
- pallets/bridge_transfer/src/mock.rs
- standalone/node/src/chain_spec.rs
- standalone/runtime/src/lib.rs
> Bridge committee

- pallets/bridge_transfer/src/lib.rs
- pallets/bridge_transfer/src/tests.rs
Now we can set a min fee and a fee scale for the specific dest chain.
> Update fee setter

- Cargo.lock
- common/types/Cargo.toml
- common/types/src/lib.rs
- crates/crypto/Cargo.toml
- pallets/phala/Cargo.toml
- standalone/pruntime/enclave/Cargo.lock
Fixed the startup issue brought by #269
```
Error: Service(Client(VersionInvalid("RuntimeConstruction(Other(\"host doesn't provide any imports from non-env module: wbindgen_placeholder:__wbindgen_describe\"))")))
```
> Fix full_crupto pollution in runtime

- pallets/phala/src/stakepool.rs
> stakepool: fix wrong MiningPool index in create()

- common/types/src/lib.rs
- standalone/pherry/src/types.rs
- standalone/pruntime/enclave/src/lib.rs
- standalone/pruntime/enclave/src/rpc_types.rs
> Prevent genesis forge problem

- pallets/phala/src/stakepool.rs
> optimize waiting withdraw pool processing

- pallets/phala/src/mining.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/stakepool.rs
> StakePool unit tests

- pallets/phala/src/stakepool.rs
- unit tests to cover deposit, reward, and withdraw
- equivalence transform for some code
- more code comments
> StakePool: unit test for reward management

- pallets/phala/src/stakepool.rs
- Use `PoolInfo::clear_user_pending_reward()` if possible
- Simplify `deposit()`
- `try_handle_waiting_withdraw` -> `try_process_withdraw_queue`
- `try_add_withdraw_pool_to_queue` -> `maybe_add_withdraw_queue`
- Removed `pending_rewards()`
- Use `saturating_accure` than `saturating_add` if possible
> stakepool: refactor `clear_user_pending_reward`

- standalone/pherry/src/main.rs
- subxt/src/rpc.rs
> pherry: wait for substrate block syncing

- pallets/phala/src/registry.rs
- pallets/phala/src/stakepool.rs
Also fix a logical error in `try_withdraw()`
> stakepool: test immediate and delayed withdraw

- pallets/phala/src/stakepool.rs
> Use Permill as the type of payout commission

- .gitignore
- scripts/coverage-pallets.sh
Run
```bash
./scripts/coverage-pallets.sh
```
Produces:
> Test coverage for phala-pallets

- pallets/phala/src/mining.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/registry.rs
- pallets/phala/src/stakepool.rs
- standalone/runtime/src/lib.rs
> Stop, force stop and reclaim stake

- Cargo.lock
- common/types/src/lib.rs
- pallets/phala/Cargo.toml
- pallets/phala/src/balance_convert.rs
- pallets/phala/src/lib.rs
- pallets/phala/src/mining.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/registry.rs
- pallets/phala/src/stakepool.rs
- standalone/pruntime/enclave/Cargo.lock
- standalone/runtime/src/lib.rs
> Basic tokenomic

- pallets/phala/src/mining.rs
- pallets/phala/src/stakepool.rs
> mining: enable OnlineMiners

- pallets/phala/src/mining.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/stakepool.rs
> mining: pay from subsidy pool, not issuing token

- pallets/phala/src/mining.rs
> mining: add update_tokenomic

- .editorconfig
- e2e/tests/typeoverride.js
- pallets/phala/src/mining.rs
- pallets/phala/src/utils/balance_convert.rs
> Add mining payout stats

- e2e/tests/typeoverride.js
- pallets/phala/src/mining.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/utils/constants.rs
- standalone/runtime/src/msg_routing.rs
> mining: update bench when got heartbeat

- crates/prpc-build/src/protos_codec_extension.rs
- standalone/pherry/src/main.rs
- standalone/pherry/src/msg_sync.rs
- standalone/pruntime/enclave/src/lib.rs
- standalone/pruntime/enclave/src/prpc_service.rs
> prpc: Better naming convention for SCALE encoded fields

- e2e/tests/fullstack.js
- Don't share the relayer sender account for two GKs
- Reduce the relayer sleep period (for faster chain in the future)
- Generate `start-node.sh`
> e2e: gk test setup improvements

- standalone/pruntime/app/src/main.rs
Avoid mistakes like https://github.com/Phala-Network/phala-blockchain/commit/6a6b97807ae84d0cb0516af28f8525c50e16b5f7
> Let's never forget to add rocket route again.

- Cargo.lock
- e2e/tests/fullstack.js
- e2e/tests/typeoverride.js
- pallets/phala/src/mock.rs
- pallets/phala/src/mq.rs
- pallets/phala/src/mq/check_seq.rs
- pallets/phala/src/registry.rs
- pallets/phala/src/stakepool.rs
- scripts/debug-cli/Cargo.toml
- scripts/debug-cli/src/main.rs
- standalone/runtime/src/lib.rs
Fixes #388 
- Add helper function `StakePool::reclaim_pool_worker()`
- Fix missing pending reward settlement
- Add `debug-cli inspect-pallet-id` to get pallet addresses
- Fix double stake problem
> StakePool fixes

- pallets/phala/src/mining.rs
- Calculate p_instant based on the last challenge time
- Allow the reset of iteration counter
> mining: correct bench calc

- standalone/pruntime/enclave/src/system/gk.rs
> gk: handle iterations < iterations_last

- pallets/phala/src/mq/check_seq.rs
- standalone/pherry/src/extra.rs
- standalone/pherry/src/main.rs
- standalone/pherry/src/msg_sync.rs
- standalone/pherry/src/runtimes.rs
- subxt/src/extrinsic/extra.rs
- subxt/src/extrinsic/mod.rs
- subxt/src/lib.rs
> pherry: config transaction longevity

- standalone/pherry/src/main.rs
- standalone/pherry/src/msg_sync.rs
This can reduce the risk of tx stuck.
> pherry: set 4 to default longevity

- standalone/pherry/src/main.rs
- standalone/pherry/src/msg_sync.rs
> pherry: Limit pherry message submission amount

- Cargo.lock
- Cargo.toml
- crates/phala-mq/Cargo.toml
- crates/phala-mq/src/types.rs
- pallets/phala/mq-runtime-api/Cargo.toml
- pallets/phala/mq-runtime-api/src/lib.rs
- pallets/phala/src/mq.rs
- pallets/phala/src/mq/check_seq.rs
- standalone/node/src/service.rs
- standalone/pherry/src/chain_client.rs
- standalone/pherry/src/msg_sync.rs
- standalone/pruntime/app/Cargo.lock
- standalone/pruntime/enclave/Cargo.lock
- standalone/rpc-ext/Cargo.toml
- standalone/rpc-ext/src/lib.rs
- standalone/rpc-ext/src/mq_seq.rs
- standalone/rpc-ext/src/storage_changes.rs
- standalone/runtime/Cargo.toml
- standalone/runtime/src/lib.rs
> Add rpc to get next mq seq in txpool.

- pallets/bridge/src/lib.rs
Porting from [PR](https://github.com/Phala-Network/khala-parachain/pull/11) in khala-parachain. This PR fix security issue exist in weight calculation of dispatch ```acknowledge_proposal``` and ```eval_vote_state```.
> bridge: fix weight calculation

- pallets/bridge/src/lib.rs
- pallets/bridge_transfer/src/lib.rs
- pallets/phala/src/mq.rs
- pallets/phala/src/stakepool.rs
Add missing `storage_version` to all pallets we made
> add storage version to all pallets

- crates/phactory/api/src/ecall_args.rs
- crates/phactory/src/benchmark.rs
- standalone/pruntime/app/src/main.rs
- standalone/pruntime/enclave/Cargo.lock
- standalone/pruntime/enclave/src/lib.rs
> phactory: Don't start to benchmark at startup by default

- crates/phactory/src/system/gk.rs
Fixes #446 
Instead of tracking `v_last`, now we track `payable`. Each time v is increased, payable increases the same amount. When payout or v is slashed, payable will be reset to zero. It's used to limit the max payout.
Please merge https://github.com/Phala-Network/prpc-protos/pull/3 as well
> gk: fix payout at v_max

- crates/phactory/api/src/lib.rs
- crates/phactory/src/light_validation/justification.rs
- crates/phactory/src/light_validation/mod.rs
- crates/phactory/src/prpc_service.rs
- e2e/package.json
- e2e/yarn.lock
- scripts/debug-cli/src/main.rs
- standalone/pherry/src/chain_client.rs
- standalone/pherry/src/main.rs
- standalone/pherry/src/runtimes.rs
- No longer assume the light client is initialized with set_id=0
- Corresponding changes in pherry
Incompatible changes introduced to pherry & pruntime.
- Existing miners can continue on mining
- New miners or miner restart must have pherry/prb & pruntime updated
- No runtime upgrade
> Midway start

- crates/phactory/api/build.rs
- crates/phactory/api/src/ecall_args.rs
- crates/phactory/src/lib.rs
- crates/phactory/src/prpc_service.rs
- scripts/debug-cli/src/main.rs
- standalone/pruntime/Makefile
- standalone/pruntime/app/Cargo.lock
- standalone/pruntime/app/Cargo.toml
- standalone/pruntime/app/src/main.rs
- standalone/pruntime/enclave/src/lib.rs
- standalone/pruntime/git-revision
Fixes https://github.com/Phala-Network/phala-blockchain/issues/456
For normal build:
```shell
$ ./target/release/debug-cli rpc get-info
PhactoryInfo {
initialized: false,
registered: false,
genesis_block_hash: None,
public_key: None,
ecdh_public_key: None,
headernum: 0,
para_headernum: 0,
blocknum: 0,
state_root: "",
dev_mode: false,
pending_messages: 0,
score: 0,
gatekeeper: Some(
GatekeeperStatus {
role: None,
master_public_key: "",
},
),
version: "0.1.0",
git_revision: "f865d583d76bca88a19dda20543a4004c5ed48be",
}
```
For dirty build (local working tree has uncommited changes):
```shell
$ ./target/release/debug-cli rpc get-info
PhactoryInfo {
initialized: false,
registered: false,
genesis_block_hash: None,
public_key: None,
ecdh_public_key: None,
headernum: 0,
para_headernum: 0, …
```
> Add pRuntime version & git revision

- pallets/phala/src/mining.rs
- pallets/phala/src/mock.rs
- standalone/runtime/src/lib.rs
> mining: minimal P to start

- standalone/pherry/src/error.rs
- standalone/pherry/src/main.rs
- standalone/pherry/src/runtimes.rs
> pherry: parachain mode fast start

- standalone/pherry/src/main.rs
> pherry: fix fast sync misalign problem

- standalone/pherry/src/main.rs
> pherry: Disable geolocaltion by default

- scripts/js/src/cleanTxPool.js
This script will find all the pools with "1 pico" withdraw request in the withdraw queue and remove the pending extrinsics from the collator's txpool by `author_removeExtrinsics`
> Temporary mitigation of issue #487

- crates/phactory/api/src/crypto.rs
Companion proto PR: https://github.com/Phala-Network/prpc-protos/pull/9
This PR introduces a new kind of SignatureType: add `<Bytes>` and `</Bytes>` to wrap the message to sign, called "Wrap Bytes" in Polkadot.js Extension. We have to support it because all the messages signed by Polkadot.js Extension are in this format.
See more at: https://github.com/polkadot-js/extension/blob/e4ce268b1cad5e39e75a2195e3aa6d0344de7745/packages/extension-dapp/src/wrapBytes.ts
> phactory: add "WrapBytes" signature types

- scripts/coverage-pallets.sh
Ignore pure comments or some macro attributes
> scripts: more accurate coverage

- pallets/phala/src/mining.rs
> Trigger repair v

- .github/workflows/build.yml
- hw.Dockerfile
- rust-toolchain
- standalone/pruntime/app/src/main.rs
- standalone/pruntime/enclave/src/libc_hacks.rs
- sw.Dockerfile
cause subxt requires edition="2021" now
> Upgrade rustc to 2021-11-11

- Cargo.lock
- crates/phala-node-rpc-ext/Cargo.toml
- crates/phala-node-rpc-ext/src/lib.rs
- crates/phala-node-rpc-ext/src/storage_changes.rs
Resolves #567
Usage:
```bash
curl http://localhost:8009 -H "Content-Type:application/json;charset=utf-8" -d   '{
>      "jsonrpc":"2.0",
>       "id":1,
>       "method":"pha_getStorageChangesAt",
>       "params": ["0xbbe41cd36d6c95d4d95f2a0c799a43979487108f10ff577ef5d2a2ce24eaac4a"]
>     }'
{"jsonrpc":"2.0","result":"0x74801cb6f36e027abb2091cfb5110ab5087f0323475657e0890fbdbf66fb24b4649e00801cb6f36e027abb2091cfb5110ab5087f06155b3cd9a8c9e5e9a23fd5dc13a5ed0120c6e7852000000000b01cb6f36e027abb2091cfb5110ab5087fb9093659d7a856809757134d2bc86e62b4def25cfda6ef3a000000000105031832e81cf642dd2ac3aad2ff5e7e6c4fa65c2de8be8154991e152c4f4d062c9511610c2dfa94bd182fa94ab9f49af03b9840a123579a9c3f4000ddce01db952f5daabe1c9f0b82bfe7c3a6a0ce44904b87cfa26b2c889a97de034c0d4798fa462b06011490ae2fd0680608bd1ad4c9ff …
```
> phala-node: add rpc pha_getStorageChangesAt

- Cargo.lock
- crates/phaxt/src/extra.rs
Update since https://github.com/paritytech/subxt/pull/322 merged.
> Update to latest subxt

- pallets/phala/src/mining.rs
> mining: postpone the tokenomic update to the end of the block

- pallets/phala/src/stakepool.rs
This PR will create a function `reconcile_withdraw_queue` that can be used to remove the bad data in the withdraw queue for any user / pool
> stakepool: reconcile_withdraw_queue

- crates/phactory/Cargo.toml
- crates/phactory/src/system/gk.rs
- crates/phactory/src/system/mod.rs
- crates/phala-mq/src/send_queue.rs
- scripts/js/src/console.js
To check whether GK's mq egresses are exactly match the ones accepted on chain.
> pRuntime: Add feature to replay and export GK's mq egress.

- crates/phactory/src/contracts/support.rs
- crates/phactory/src/system/mod.rs
As it is needed by the btc-bot-price demo.
> More info in contract context

- Cargo.lock
- crates/pink/pink-extension/Cargo.toml
- crates/pink/pink-extension/src/chain_extension.rs
- crates/pink/pink-extension/src/chain_extension/http_request.rs
- crates/pink/pink-extension/src/chain_extension/signing.rs
- crates/pink/pink-extension/src/lib.rs
- standalone/pruntime/enclave/Cargo.lock
- standalone/pruntime/pruntime/Cargo.lock
This allow to invoke extention at anywhere.
> Self free pink_extension instantiate

- crates/phactory/src/benchmark.rs
- crates/phactory/src/prpc_service.rs
- crates/phactory/src/side_task.rs
- standalone/pruntime/enclave/src/lib.rs
- standalone/pruntime/pruntime/src/runtime.rs
> Pause benchmark while syncing history blocks

- crates/phactory/src/benchmark.rs
- crates/phactory/src/prpc_service.rs
- crates/phactory/src/side_task.rs
- standalone/pruntime/enclave/src/lib.rs
> Back port the PR #669 "Pause benchmark"

- e2e/src/utils/pruntime.js
- scripts/js/build_proto.sh
- scripts/js/package.json
- scripts/js/src/console.js
- scripts/js/src/dumpLockChart.js
- scripts/js/src/proto/prpc.d.ts
- scripts/js/src/proto/prpc.js
- scripts/js/src/proto/pruntime_rpc.d.ts
- scripts/js/src/proto/pruntime_rpc.js
- scripts/js/src/utils/pruntime.js
- scripts/js/src/worker-snapshot/dump.js
- scripts/js/yarn.lock
- better transact with fee check
- switch from http pruntime rpc to prpc
> console: improve xcmp transact

- crates/pink/src/runtime/extension.rs
Since the deterministic of Commands is a hard requirement, we need to be careful when implementing a ext function which available for Commands. The previous implementation requires checking the calling context (query or command) in each funtion body which is likely a footgun.
This PR explictly seperate the impl ExtBackend for query and command so that we can less likely shoot ourselves in the foot when we implement new ext functions.
> pink-ext: Split extension impl into query and command

- crates/phactory/src/system/gk.rs
- crates/phala-types/src/lib.rs
- pallets/phala/src/migrations/mod.rs
- pallets/phala/src/mining.rs
> gk: enable full payout with insufficent delta v

- crates/pink/src/contract.rs
> pink: treat Ok(REVERT) as instantiate failed

- crates/pink/src/runtime/extension.rs
> pink-httpclient: Auto add "Content-Length" header for POST

- pallets/phala/src/stakepool.rs
Instead of checking the staking cap immediately, this PR postpone the check after processing the withdraw queue. So people don't need to increase the cap before adding stake to swap the withdrawing funds
> stakepool: post check stake cap

- Cargo.lock
- pallets/phala/Cargo.toml
- pallets/phala/src/fat.rs
- pallets/phala/src/lib.rs
- pallets/phala/src/mining.rs
- pallets/phala/src/mq.rs
- pallets/phala/src/registry.rs
- pallets/phala/src/stakepool.rs
- pallets/phala/src/utils/accumulator.rs
- pallets/phala/src/utils/mod.rs
- force_set_benchmark_duration governed by GovernanceOrigin
- remove panic!
- bump phala-pallets to 4.1.0
> docs & nits in registry

- crates/phactory/api/src/storage_sync.rs
- crates/phactory/src/prpc_service.rs
> pruntime: Ignore already synced headers instead of rejecting it

- crates/phactory/api/Cargo.toml
- crates/phactory/api/src/ecall_args.rs
- crates/phactory/api/src/storage_sync.rs
- crates/phactory/src/lib.rs
- crates/phactory/src/prpc_service.rs
- crates/phala-trie-storage/src/lib.rs
- standalone/pruntime/app/Cargo.lock
- standalone/pruntime/app/src/main.rs
- standalone/pruntime/enclave/Cargo.lock
- standalone/pruntime/enclave/Cargo.toml
- standalone/pruntime/enclave/src/lib.rs
- standalone/replay/src/replay_gk.rs
This can significantly improve the sync speed.
> [Backport] Configurable gc interval of the db

- standalone/headers-cache/src/main.rs
To see the first and the last block numbers in a grabbed binary file.
> headers-cache: Add subcommand inspect

- pallets/phala/src/stakepool.rs
Add function to backfill missing reward due to #763
> Backfill missing reward for issue 763

- crates/phactory/src/contracts/support.rs
- crates/phactory/src/system/mod.rs
- crates/pink/examples/start_sidevm/lib.rs
- crates/pink/pink-extension/src/lib.rs
- crates/pink/sidevm/examples/httpserver/src/lib.rs
- crates/pink/sidevm/examples/tcpclient/src/lib.rs
- crates/pink/sidevm/host-runtime/src/service.rs
- crates/pink/sidevm/sidevm/src/net.rs
Should use `tokio::io::BufReader` instead.
> sidevm: Remove 'impl AsyncBufRead for TcpStream'

- Cargo.lock
- pallets/phala/Cargo.toml
> Phala pallet: Remove unused libsecp256k1

- Cargo.lock
- crates/phactory/Cargo.toml
- crates/phactory/api/Cargo.toml
- crates/phala-crypto/Cargo.toml
- crates/phala-mq/Cargo.toml
- crates/phala-node-rpc-ext/Cargo.toml
- crates/phala-serde-more/Cargo.toml
- crates/phala-trie-storage/Cargo.toml
- crates/phala-types/Cargo.toml
- crates/pink/Cargo.toml
- native-nostd-hasher/Cargo.toml
- pallets/bridge/Cargo.toml
- pallets/bridge_transfer/Cargo.toml
- pallets/kitties/Cargo.toml
- pallets/phala/Cargo.toml
- pallets/phala/mq-runtime-api/Cargo.toml
- scripts/debug-cli/Cargo.toml
- standalone/executor/Cargo.toml
- standalone/node/Cargo.toml
- standalone/pherry/Cargo.toml
- standalone/replay/Cargo.toml
- standalone/rpc/Cargo.toml
- standalone/runtime/Cargo.toml
migrate cargo from submodule to git
> migrate cargo from submodule to git

- Cargo.lock
- crates/phala-rocket-middleware/Cargo.toml
- crates/phala-rocket-middleware/src/time_meter.rs
- standalone/headers-cache/Cargo.toml
- standalone/headers-cache/src/main.rs
- standalone/headers-cache/src/web_api.rs
The stupid Rocket doesn't show the HTTP status code in the log. Let's do it.
> headers-cache: Log http status

- Cargo.lock
- pallets/phala/Cargo.toml
- standalone/pruntime/Cargo.lock
Upstream backported https://github.com/paritytech/substrate/pull/11707
> Upgrade Polkadot 0.9.24 again

- crates/phactory/Cargo.toml
- crates/phactory/api/build.rs
- crates/phactory/src/system/gk.rs
- standalone/replay/Cargo.toml
It is not necessary to keep them in memory in normal GKs.
> gk: Put the statitstics fields under a feature gate

- .github/actions/install_toolchain/action.yml
- .github/workflows/build-js-script.yml
- .github/workflows/build.yml
- Removed no longer used SGX SDK staff
- Upgrade actions
> Upgrade GitHub Actions

- Cargo.lock
- crates/pink/examples/unittests/.gitignore
- crates/pink/examples/unittests/Cargo.toml
- crates/pink/examples/unittests/lib.rs
- crates/pink/pink-extension-runtime/Cargo.toml
- crates/pink/pink-extension-runtime/src/lib.rs
- crates/pink/pink-extension-runtime/src/mock_ext.rs
- crates/pink/pink-extension/Cargo.toml
- crates/pink/pink-extension/src/chain_extension.rs
- crates/pink/src/runtime/extension.rs
Usage:
```rust
let random_bytes = pink::ext().getrandom(32);
```
> pink-ext: Add getrandom

- crates/pink/sidevm/examples/host/Cargo.toml
- crates/pink/sidevm/examples/host/README.md
- crates/pink/sidevm/examples/host/src/main.rs
- crates/pink/sidevm/examples/host/src/web_api.rs
For better debug experience.
Usage: 
```bash
ROCKET_PORT=8003 sidevm-host path/to/the/sideprog.wasm&
curl -d hello localhost:8003/push/message
```
> sidevm-host: Add http api to push messages to guest program.

- crates/phala-types/src/contract.rs
- pallets/phala/src/mq.rs
It should work. However, haven't tested it yet.
> pallet: Add fn push_ink_message

- Cargo.lock
- Cargo.toml
- crates/pink/pink-extension/Cargo.toml
- crates/pink/pink-extension/src/chain_extension/http_request.rs
- crates/pink/pink-extension/src/lib.rs
- crates/pink/pink-s3/.gitignore
- crates/pink/pink-s3/Cargo.toml
- crates/pink/pink-s3/README.md
- crates/pink/pink-s3/src/lib.rs
This PR extracted the S3 protocol handling codes from https://github.com/christopherfkk/fat-contract-s3-sync.
Turn it into a library.
I don't have an AWS S3 account to test it. Instead, I tested it with my self-hosted [garage](https://git.deuxfleurs.fr/Deuxfleurs/garage) server: https://s3.kvin.wang:8443
It has been published at https://crates.io/crates/pink-s3
> Add pink-s3

- Cargo.lock
- crates/phactory/Cargo.toml
- crates/phactory/api/src/lib.rs
- crates/phactory/src/prpc_service.rs
- standalone/pruntime/Cargo.lock
- standalone/pruntime/src/api_server.rs
Proto definition: https://github.com/Phala-Network/prpc-protos/pull/24
> Add pRPC http_fetch for PSN testing

- standalone/pruntime/Makefile
To make the old docs compatible.
> Add Makefile for pruntime

- crates/phactory/api/build.rs
- crates/phactory/src/bin_api_service.rs
- standalone/pruntime/src/api_server.rs
- standalone/pruntime/src/runtime.rs
Difference between `/info` and `/get_info`:
/get_info
```bash
$ curl localhost:8000/get_info
{"payload":"{\"blocknum\":6,\"dev_mode\":true,\"ecdh_public_key\":\"3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d\",\"gatekeeper\":{\"master_public_key\":\"\",\"role\":0},\"genesis_block_hash\":\"ae46c0c54e2cfc60a095bd5dcfcae2005608fed88398e87e5ca2f3973a8bcb55\",\"git_revision\":\"8cc2c91bb05af48d1487574edf67b84b9bb8a8ec-dirty\",\"headernum\":6,\"initialized\":true,\"memory_usage\":{\"rust_peak_used\":7447633,\"rust_used\":1733183,\"total_peak_used\":8404076},\"network_status\":{\"config\":null,\"public_rpc_port\":null},\"number_of_clusters\":0,\"number_of_contracts\":0,\"para_headernum\":0,\"pending_messages\":1,\"public_key\":\"3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2 …
```
> Simplify get_info_json && add /info

- crates/phactory/api/build.rs
- crates/phactory/src/prpc_service.rs
- crates/phactory/src/system/mod.rs
- e2e/src/fullstack.js
- e2e/src/proto/pruntime_rpc.d.ts
- e2e/src/proto/pruntime_rpc.js
- scripts/debug-cli/src/query.rs
> Refactor get_info response structure

- crates/phactory/src/system/mod.rs
- crates/phala-types/src/lib.rs
- dockerfile.d/01_apt_gramine.sh
- e2e/src/fullstack.js
- e2e/src/proto/pruntime_rpc.d.ts
- e2e/src/proto/pruntime_rpc.js
- pallets/phala/src/registry.rs
- standalone/pruntime/Cargo.lock
Can be used to determine feature flags.
> Add pruntime consensus version

- crates/phactory/src/storage.rs
Part of #828
This pruntime side change should be released before the chain-side.
> pruntime: Also pick messages from OutboundMessagesV2

- .gitmodules
And use the i2pd repo from Phala-Network.
> Clean unused submodules

- Cargo.lock
- crates/phala-node-rpc-ext/Cargo.toml
- crates/phala-node-rpc-ext/types/Cargo.toml
- crates/phala-trie-storage/Cargo.toml
- crates/pink/Cargo.toml
- standalone/pruntime/Cargo.lock
I'm accident change this one which shouldn't do this time
> Keep using impl-serde 0.3.2, this should be upgraded in next time

- pallets/phala/src/registry.rs
add registry events for phala app upgrading.
> add registry events

- pallets/phala/src/compute/basepool.rs
- pallets/phala/src/compute/pawnshop.rs
- pallets/phala/src/compute/poolproxy.rs
- pallets/phala/src/compute/stakepoolv2.rs
- pallets/phala/src/compute/vault.rs
- pallets/phala/src/lib.rs
- pallets/phala/src/migrations/mod.rs
> comments for stakepoolv2

- crates/phactory/src/prpc_service.rs
- standalone/pruntime/src/api_server.rs
> prpc: Split GetNetworkConfig out from GetInfo

- pallets/phala/src/stakepool.rs
Restrict remove worker condition to adjust further migration for stakepool v2.
> Restrict remove worker condition

- scripts/fix_pruntime_justification_error.sh
0. Added explanation of what the script does
1. Split out envars at the top in a 'To Edit' section
2. Install deps, curl, jq
3. Check the envars are set
4. Check running as root
5. Made it idempotent by only fixing workers on a specific block(s)
6. Give feedback on overall progress. Make two curl calls, one for a list of all workers, and one for a list stuck, and count each.
7. Push docker logging output to dev/null , so you can actually tell what the fuck is happening
> pRuntime critical fix script polish

- pallets/phala/src/registry.rs
Let's turn the Clippy checking to a hard requirement to merge in the CI from now on.
> Fix clippy warnings

- pallets/phala/src/mining.rs
@jasl Could you test it with a testnet with some real computing workers?
> Add chain API to pause heartbeat

- crates/phactory/src/lib.rs
Cherrypick of https://github.com/Phala-Network/phala-blockchain/pull/1054
> Don't save command line args in checkpoint

- crates/sidevm/host-runtime/src/env.rs
- crates/sidevm/host-runtime/src/service.rs
This fixes the following misordered logs
> sidevm: Fix misordering of messages

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/stake_pool_v2.rs
- pallets/phala/src/compute/vault.rs
- pallets/phala/src/compute/wrapped_balances.rs
- pallets/phala/src/lib.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/test.rs
- standalone/runtime/src/lib.rs
Please review this with https://github.com/Phala-Network/phala-blockchain/actions/runs/3669336144/jobs/6203096377#step:5:1912
> Cargo clippy for stakepool v2

- pallets/phala/src/compute/stake_pool_v2.rs
> No check for migration mint

- pallets/phala/src/compute/stake_pool_v2.rs
- standalone/runtime/src/lib.rs
> Change assetid

- pallets/phala/src/compute/stake_pool_v2.rs
> Fix StakePool v2 migration data corruptions

- Cargo.lock
- Cargo.toml
- crates/pink-libs/subrpc/Cargo.toml
- crates/pink-libs/subrpc/src/lib.rs
- crates/pink-libs/subrpc/src/objects.rs
- crates/pink-libs/subrpc/src/objects/era.rs
- crates/pink-libs/subrpc/src/rpc.rs
- crates/pink-libs/subrpc/src/ss58.rs
- crates/pink-libs/subrpc/src/storage.rs
- crates/pink-libs/subrpc/src/transaction.rs
It is moved from https://github.com/Phala-Network/phat-offchain-rollup/tree/main/phat/crates/subrpc to here.
> Add pink-subrpc and publish it to crates.io

- pallets/offchain-rollup/src/anchor.rs
- pallets/offchain-rollup/src/mock.rs
- pallets/offchain-rollup/src/types.rs
- standalone/runtime/src/lib.rs
This PR implements the off-chain rollup queue according to the given API design in https://github.com/Phala-Network/phala-blockchain/pull/1073.
> pallet: Implement rollup-queue

- pallets/offchain-rollup/src/anchor.rs
> Offchain rollup queue api draft

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/stake_pool_v2.rs
- pallets/phala/src/compute/wrapped_balances.rs
- pallets/phala/src/fat_tokenomic/tests/mock.rs
- pallets/phala/src/mock.rs
- pallets/phala/src/test.rs
- standalone/runtime/src/lib.rs
> Fix unwrap and lock_account

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/stake_pool_v2.rs
> Remove properties in khala

- pallets/phala/src/compute/base_pool.rs
> push for property delete

- pallets/phala/src/compute/base_pool.rs
> push for iteration improve

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/test.rs
> Add shares transfer

- crates/phactory/src/light_validation/mod.rs
- scripts/get-state.sh
- scripts/storage-analyze.py
With these scripts, we addressed the resource leak in `RmrkCore::Properties` this morning.
```
0x5bef2c5471aa9e955551dc810f5abb 262971099
0xb71c310d8c830d345ee1c1b84566a8 14408022
0x0d746931e7a6bfd47fbcccfd71984a 8226648
0x5e8a19e3cd1b7c148b33880c479c02 7515862
0x75e3ed3f59e45643ed1149ad80929c 4365694
0x26aa394eea5630e07c48ae0c9558ce 3789815
0x2f039a6a7f13e94b9545257e54062a 3390574
0x00f8eafbad3b4a32114491ad7e1249 2171795
0x3a636f6465 1247567
0x66b8232d707a1e10cc0cc5a75b738a 867102
0xfcf02af62786f6514fecf014aae642 669662
0x1466de7f00add77dbab4df042b8c4a 508542
0x43cdcd39d5edb1d16e24fa028edde0 482267
0x682a59d51ab9e48a8c8cc418ff9708 389706
0x5f27b51b5ec208ee9cb25b55d87282 271869
0xc2261276cc9d1f8598ea4b6a74b15c 209702
0xf2794c22e353e9a839f12faab03a91 47571
0x2aeddc77fe58c98d50bd37f1b90840 …
```
> Scripts for storage debugging.

- pallets/phala/src/compute/vault.rs
> merge for vault owner

- Cargo.lock
- crates/pink-libs/subrpc/Cargo.toml
- crates/pink-libs/subrpc/src/lib.rs
- crates/pink-libs/subrpc/src/objects.rs
- crates/pink-libs/subrpc/src/objects/era.rs
Reverts Phala-Network/phala-blockchain#1102
> Revert "Some update for subrpc"

- Cargo.lock
- crates/pink-libs/subrpc/Cargo.toml
> Bump subrpc to 0.2.0

- standalone/pruntime/app/src/main.rs
This fixes https://github.com/Phala-Network/phala-blockchain/issues/1107
> pruntime v0: Exit when enclave crashed

- Cargo.lock
- pallets/phala/src/mock.rs
- standalone/node/tests/common.rs
- standalone/prouter/Cargo.lock
- standalone/pruntime/Cargo.lock
- standalone/runtime/src/lib.rs
RMRK backported some upstream changes, this PR upgrade to latest RMRK and Substrate commit to align with Khala.
It shouldn't change any behavior, so secure to merge
> Upgrade to latest Substrate (0.9.37) and RMRK commit

- crates/phaxt/src/chain_api.rs
- pallets/phala/src/registry.rs
- standalone/pherry/src/chain_client.rs
> pallet_registry: Record worker first registered block number

- crates/phactory/src/lib.rs
- crates/phactory/src/prpc_service.rs
- standalone/pruntime/src/api_server.rs
Required by the handover script.
> Add prpc.TakeCheckpoint and ts in get_info

- standalone/headers-cache/src/grab.rs
- standalone/headers-cache/src/main.rs
- standalone/pherry/src/headers_cache.rs
Improvements:
@jasl Please update the pherry docker image with this PR to reduce the TCP connections to headers-cache.
> headers-cache: Some improvements

- crates/phactory/src/lib.rs
The saved file content:
```
$ls data/storage_files/
checkpoint.seal-000000035  checkpoint.seal-000000035.info.json  checkpoint.seal-000000039  checkpoint.seal-000000039.info.json
$cat data/storage_files/checkpoint.seal-000000035.info.json
{
"initialized": true,
"registered": true,
"genesis_block_hash": "fa09787de704d57991c2f84e675f328a7f5346bf841dfb60424b22bf1c43328d",
"public_key": "3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d",
"ecdh_public_key": "3a3d45dc55b57bf542f4c6ff41af080ec675317f4ed50ae1d2713bf9f892692d",
"headernum": 37,
"para_headernum": 0,
"blocknum": 36,
"state_root": "1f334d494b53c66264d49433c508ec6059de425432ed243adebd2fd269f2c98c",
"dev_mode": true,
"pending_messages": 1,
"score": 0,
"gatekeeper": {
"role": 0,
"master_public_key": ""
},
"version": …
```
> pruntime: Save get_info along side the checkpoint file

- Cargo.lock
- crates/pink-libs/s3/Cargo.toml
- crates/pink-libs/s3/example/.gitignore
- crates/pink-libs/s3/example/Cargo.toml
- crates/pink-libs/s3/example/lib.rs
- crates/pink-libs/s3/src/lib.rs
> pink-s3: Fix compilation error

- Cargo.lock
- crates/pink-libs/subrpc/Cargo.toml
- crates/pink-libs/subrpc/src/hasher.rs
- Fix compile issue on no-std env
- Add hash function Twox64
> Release subrpc v0.4.1

- scripts/js/src/console.js
- Support sends XCMP message to relaychain as root
- Fix motion construction issue on gov-v2
> Update console script

- Cargo.lock
- crates/pink-libs/subrpc/Cargo.toml
- crates/pink-libs/subrpc/src/hasher.rs
- crates/pink-libs/subrpc/src/storage.rs
- Fix storage map key calculation
> Bump subrpc 0.4.2

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/test.rs
Correct the actual free balances that could be withdraw.
> fix further bug in extrem conditon

- .github/workflows/build.yml
will relax more usable disk space for building our artifacts
> Improve GitHub Actions scripts for large disk space

- scripts/js/src/console.js
- standalone/replay/src/main.rs
- standalone/replay/src/replay_gk.rs
- console.js: grab GK egress also handle batch extrinsic
- gk-replay: Support headers-cache and `--stop-at`
> Add some GK egress debug features

- e2e/yarn.lock
- frontend/packages/sdk/package.json
- frontend/packages/sdk/yarn.lock
This PR updates the version of dependencies as a regular update.
> dependencies(jssdk): up-to-date polkadot-js libs

- standalone/headers-cache/src/grab.rs
This is expected to fix the HeaderHashMismatch issue when syncing with headers-cache grabbed data.
cc @krhougs @l00k
> headers-cache: Don't grab unfinalized blocks

- crates/phactory/src/lib.rs
- crates/phactory/src/prpc_service.rs
- crates/phactory/src/system/mod.rs
- e2e/src/fullstack.js
- e2e/src/utils/pruntime.js
The search path was wrong when trying to remove checkpoints.
cc @jasl @doyleguo
> Fix non-first GK auto-restart issue

- crates/phala-scheduler/src/task_scheduler.rs
The 'waker' may change between each polling cycle. Therefore, it should be updated during each poll. Without this fix, there's a risk that the waker could inadvertently wake up an incorrect thread, causing the actual task to remain in a perpetual sleep state.
While we have not yet encountered this issue, it remains a theoretical concern.
> Sidevm scheduler: Update wakers for ready tasks

- Cargo.lock
- crates/phaxt/Cargo.toml
- crates/phaxt/src/dynamic/tx.rs
- crates/phaxt/src/lib.rs
Big change again: https://github.com/paritytech/subxt/releases/tag/v0.29.0
> Upgrade subxt 0.29.0

- .github/workflows/build-nightly-release.yml
Not sure whether it would work. No way to test it. Just merge and look for the result.
> CI: Add monthly build

- crates/pink-drivers/system/lib.rs
- crates/pink-drivers/tokenomic/lib.rs
- crates/pink/pink-extension/src/system.rs
Reverts Phala-Network/phala-blockchain#1305
Reverting due to the e2e failure after merged.
> Revert "pink: Add API driver_history"

- crates/pink-drivers/system/lib.rs
- crates/pink-drivers/tokenomic/lib.rs
- crates/pink/pink-extension/src/system.rs
Reverts Phala-Network/phala-blockchain#1309
Let's bring the PR back since the e2e test was sovled on master.
> Revert "Revert "pink: Add API driver_history""

- Cargo.lock
- Cargo.toml
- crates/phactory/api/src/ecall_args.rs
- crates/phactory/pal/src/lib.rs
- crates/phactory/src/prpc_service.rs
- crates/phala-clap-parsers/Cargo.toml
- crates/phala-clap-parsers/src/duration.rs
- crates/phala-clap-parsers/src/lib.rs
- standalone/phat-poller/Cargo.toml
- standalone/phat-poller/src/args.rs
- standalone/pruntime/Cargo.lock
- standalone/pruntime/Cargo.toml
- standalone/pruntime/src/ias.rs
- standalone/pruntime/src/main.rs
- standalone/pruntime/src/pal_gramine.rs
> pruntime: Configurable RA timeout and retries

- pallets/phala/src/phat.rs
That causes Phat UI doesn't list it in the workers list.
> Fix added worker missing in ClusterInfo

- standalone/prb/src/datasource.rs
This PR make the PRB substrate rpc `max_concurrent_requests` configurable and default to `1024` to resolve the `RPC error: Configured max number of request slots exceeded`.
@l00k
> prb: Configurable max concurrent requests

- dockerfile.d/01_apt.sh
- dockerfile.d/01_apt_gramine.sh
See also:
https://github.com/orgs/community/discussions/47863
https://github.com/actions/runner-images/issues/7192
> Fix error in CI when installing dependecies

- Cargo.lock
- crates/pink-libs/s3/Cargo.toml
- crates/pink-libs/s3/README.md
- crates/pink-libs/s3/example/lib.rs
- crates/pink-libs/s3/src/lib.rs
Remove the constrained input and allow for return of full response from pink-s3 crate.
> Update pink s3

- Cargo.lock
- crates/phala-rocket-middleware/Cargo.toml
- crates/sidevm/host/Cargo.toml
- standalone/headers-cache/Cargo.toml
- standalone/headers-cache/src/web_api.rs
- standalone/headers-cache/src/web_api/auth.rs
- standalone/phat-poller/Cargo.toml
- standalone/pruntime/Cargo.lock
- standalone/pruntime/Cargo.toml
- standalone/sfq-test/Cargo.toml
Update rocket to 0.5.0 official release.
> Update rocket to 0.5.0

- standalone/prb/src/datasource.rs
The `known_blocks` is a factor determines the search range of the `auth_set_change`, so it should be taken into account when constructing the cache key.
This could potentially resolve the error `bad justifacation`.
> prb: Fix incorrect cache key for auth_set_change

- pallets/phala/src/compute/base_pool.rs
- pallets/phala/src/compute/stake_pool_v2.rs
- pallets/phala/src/compute/vault.rs
- pallets/phala/src/compute/wrapped_balances.rs
- standalone/runtime/src/lib.rs
Part of the resolution of [this forum post](https://forum.phala.network/t/vault-owner-misconduct-disclosure-and-solutions/3889)
> compute: add reimbursement feature

- standalone/prb/src/datasource.rs
- standalone/prb/src/tx.rs
- standalone/prb/src/worker.rs
Add more cache to avoid unnecessary node calls
> prb: improve sync performance and fix bugs

- e2e/src/fullstack.js
Since the JS-SDK provides a way to switch the pruntime endpoint, let's properly implement the syncBarrier checker.
> e2e: Implement syncBarrier properly

- crates/phala-allocator/Cargo.toml
To be used in other projects such as sidevm-quickjs
> Publish phala-allocator on crates.io

- Cargo.lock
- crates/phactory/api/Cargo.toml
- crates/phactory/api/src/crypto.rs
- crates/phactory/api/src/crypto/eip712.rs
- crates/phactory/src/prpc_service.rs
The formula:
```
let evm_address = keccak256(pubkey)[12..];
let origin = evm_address + b"@evm_address";
```
> pruntime: Address mapping from H160 in query

- pallets/phala/src/compute/vault.rs
Round error may occur when calculating the share change in `do_gain_owner_share()`. This PR fixes the round error.
> Vault: fix round error in do_gain_owner_share

- .github/actions/install_toolchain/action.yml
- crates/phactory/api/src/proto_generated/mod.rs
- crates/phactory/src/light_validation/types.rs
- crates/phactory/src/system/gk.rs
- crates/phala-mq/src/simple_mpsc.rs
- crates/pink/runtime/src/runtime.rs
- crates/pink/runtime/src/runtime/pallet_pink.rs
- crates/sgx-attestation/src/ias.rs
- dockerfile.d/05_rust.sh
- rust-toolchain.toml
- standalone/prb/src/db.rs
`async` and `impl Trait` in trait are supported since 1.75.
> Upgrade Rustc to 1.75

- Cargo.lock
- crates/phactory/Cargo.toml
- standalone/pruntime/Cargo.lock
- standalone/pruntime/Cargo.toml
This PR bumps pPuntime to v2.2.0
> pRuntime v2.2.0

- crates/phactory/src/lib.rs
1. Save the checkpoint first then save the info JSON.
2. If the info JSON is not existed, remove the checkpoint file.
> pRuntime: remove uncompleted checkpoint

- frontend/packages/sdk/package.json
- frontend/packages/sdk/src/actions/estimateContract.ts
- frontend/packages/sdk/src/actions/sendPinkCommand.ts
- frontend/packages/sdk/src/actions/sendPinkQuery.ts
- frontend/packages/sdk/src/contracts/PinkBlueprint.ts
- frontend/packages/sdk/src/contracts/PinkCode.ts
- frontend/packages/sdk/src/contracts/PinkContract.ts
- frontend/packages/sdk/src/contracts/PinkLoggerContract.ts
- frontend/packages/sdk/src/index.ts
- frontend/packages/sdk/src/pruntime/WorkerAgreementKey.ts
- frontend/packages/sdk/src/pruntime/coders.ts
- frontend/packages/sdk/src/pruntime/pinkQuery.ts
- frontend/packages/sdk/src/types.ts
- frontend/packages/sdk/src/utils/abi/toAbi.ts
- frontend/packages/sdk/src/utils/hex.ts
- frontend/packages/sdk/src/utils/signAndSend.ts
See https://github.com/Phala-Network/phala-blockchain/pull/1536
> JS-SDK: Contract Actions

- Cargo.lock
- crates/phactory/Cargo.toml
- crates/phactory/src/prpc_service.rs
- crates/pink/chain-extension/Cargo.toml
- crates/pink/chain-extension/src/lib.rs
- crates/sgx-attestation/Cargo.toml
- crates/sgx-attestation/src/ias/report.rs
- standalone/prouter/Cargo.lock
- standalone/pruntime/Cargo.lock
This fixes the audit report https://github.com/code-423n4/2024-03-phala-network-findings/issues/65
> Update reqwest to 0.11.27

- crates/pink/runtime/src/runtime/extension.rs
- crates/pink/runtime/tests/test_pink_contract.rs
To match the doc. This fixes the audit report https://github.com/code-423n4/2024-03-phala-network-findings/issues/50
> pink: Remove system requirements for balance_of

- crates/pink/chain-extension/src/local_cache.rs
This fixes the audit report https://github.com/code-423n4/2024-03-phala-network-findings/issues/44
> pink: Fix expired cache can be recovered

- crates/pink/chain-extension/src/lib.rs
This resolves the audit report https://github.com/code-423n4/2024-03-phala-network-findings/issues/43
> pink: Fix potential integer overflow

- crates/pink/runtime/src/runtime/extension.rs
This PR partially resolves the audit report https://github.com/code-423n4/2024-03-phala-network-findings/issues/11.
The other issues in the report would not likely be resolved in short term.
> pink: Minor internal type rename

- crates/phala-rocket-middleware/Cargo.toml
- crates/phala-rocket-middleware/src/request_tracer.rs
- standalone/pruntime/src/api_server.rs
To be used by the new projects.
> Publish phala-rocket-middleware to crates.io

- standalone/headers-cache/src/grab.rs
- standalone/headers-cache/src/main.rs
- standalone/pherry/src/headers_cache.rs
Used when debuging issues on PoC6.
> HC: Support for grabing solo chain data

- frontend/packages/sdk/README.md
- Corrected a typo: `Adavantage` → `Advantage`.
> Error README.md

- frontend/packages/sdk/scripts/build_proto.sh
- frontend/packages/sdk/src/actions/estimateContract.ts
- frontend/packages/sdk/src/actions/sendPinkQuery.ts
- frontend/packages/sdk/src/contracts/PinkBlueprint.ts
- frontend/packages/sdk/src/contracts/PinkContract.ts
- frontend/packages/sdk/src/contracts/PinkLoggerContract.ts
- frontend/packages/sdk/src/pruntime/pinkQuery.ts
- frontend/packages/sdk/src/pruntime/proto/index.d.ts
- frontend/packages/sdk/src/pruntime/proto/index.js
> SDK: Adds blocknum in query response
