Phala-Network/phala-blockchain

phost/src/main.rs, pruntime/app/src/main.rs, pruntime/enclave/src/lib.rs
This PR is a **workaround** that attempting to reduce protential stress of miners which in the same pool sending too many heartbeats at the same time.
This PR includes:
- mining controller can call PRuntime's `/ping` to generate a heartbeat, the return value can be ignored
- `phost` add a new arg `--fetch-heartbeat-from-buffer`
mining controller call PRuntime's `/ping` at will, then `phost` can get the generated heartbeat and send it to the chain
=> Flexible heartbeat

pruntime/enclave/src/lib.rs
pRuntime marked it initialized even if the process fails at some point. This fix move the setting to the end of the function.
Tested:
./console.sh init
./console.sh get_info
=> pruntime: Fix setting initialized too early

common/types/src/lib.rs, pallets/phala/src/lib.rs, pallets/phala/src/tests.rs, runtime/src/lib.rs
Fix the inconsistent state when a miner registers more than once
Tested:
unit tests
=> pallet: Handle re-register correctly

Cargo.lock, common/types/src/lib.rs, pallets/phala/Cargo.toml, pallets/phala/src/lib.rs, pallets/phala/src/migrations_3_0_0.rs, pallets/staking/Cargo.toml, pruntime/enclave/Cargo.lock, runtime/Cargo.toml, runtime/src/lib.rs, scripts/js/dumpPhalaModuleStates.js
As a dependency of computation tasks, we want to make sure the storage `online_worker` is consistent with the actual online worker (i.e. "Mining" or "MiningStopping"), so that the pRuntime can validate the number of the storage map entries matches the synced data (i.e. no skipped entry).
In order to do that, we first added a js script to check phala on-chain data consistency, found the problem, fixed in another commit, and we are going to perform a storage migration to fix the inconsistency.
This PR will upgrade the runtime to v21.
Storage migration:
- Cleanup incorrect worker state (missing machine_id)
- Reconcile online_worker and total_power
Tested:
x-validated by: dumpPhalaModuleState.js
=> Fix mining state inconsistency + data migration

common/types/src/lib.rs, pallets/phala/src/constants.rs, pallets/phala/src/lib.rs, pallets/phala/src/tests.rs
- Add `confidence_level` field to `WorkerState`, smaller means the worker can do more privacy-sensitive tasks
- Computing tasks will dispatch to suitable workers based on this field
- `0` is the special level, only set which registered by `force_register`
- Use for special usages, not attending normal mining or compting tasks
- Genesis gatekeeper will be set to `128`
- Refactor `register_worker`
- Improve RA report validation
- Validate signing cert expires date
- Validate report's timestamp, only accept generated within 60s
- Rank `confidence_level` based on `isvEnclaveQuoteStatus`
- Hardcode the mapping in pallet
- `1`: `OK`
- `2`: `SW_HARDENING_NEEDED`
- `3`: `CONFIGURATION_NEEDED`, `CONFIGURATION_AND_SW_HARDENING_NEEDED`
- `4`: `GROUP_OUT_OF_DATE`
- Determine the worker can be …
=> Confidental level and refactor register_worker

standalone/pruntime/enclave/.cargo/config.toml, standalone/pruntime/enclave/Makefile
Much better than putting it to a Makefile, because now it should be recognized by all the toolchains
=> Set SKIP_WASM_BUILD by .cargo/config.toml

pallets/phala/src/registry.rs, standalone/pruntime/app/src/main.rs, standalone/pruntime/enclave/src/benchmark.rs, standalone/pruntime/enclave/src/lib.rs, standalone/pruntime/enclave/src/system/mod.rs
1. pallet-registry: Redo benchmark each time worker registered.
2. pRuntime: log estimated bench score.
=> Minor amending to #248

standalone/pruntime/enclave/src/benchmark.rs, standalone/pruntime/enclave/src/lib.rs
Added benchmark score in the enclave api `get_info`.
Usage example:
```shell
curl -d '{"input": {}, "nonce": {}}' -H "Content-Type: application/json"  http://localhost:8000/get_info 2>/dev/null | jq -r .payload | jq .score
```
=> pruntime: Add benchmark score in api:get_info.

Cargo.lock, standalone/pruntime/app/Cargo.lock, standalone/pruntime/enclave-api/Cargo.toml, standalone/pruntime/enclave-api/src/lib.rs, standalone/pruntime/enclave/Cargo.lock, standalone/pruntime/enclave/src/lib.rs, standalone/pruntime/enclave/src/light_validation/mod.rs, standalone/pruntime/enclave/src/storage_sync.rs, standalone/pruntime/enclave/src/system/mod.rs
The sync_header and part of dispatch_block code was splitted to a seperate crate for better flexibility.
Later, parachain syncing codes will based on the PR.
=> Refactor the chain storage synchronizing code

standalone/pruntime/app/src/main.rs, standalone/pruntime/enclave/src/lib.rs, standalone/pruntime/enclave/src/prpc_service.rs
Fit get_egress_messages output size to the ENCLAVE output buffer.
=> pRuntime: Limit get_egress_messages output size

standalone/pherry/src/main.rs
Trying to fix pherry panicing when the finalized block hash not found from the collator node.
=> pherry: Handle "block hash not found"

e2e/tests/typeoverride.js, pallets/phala/src/mining.rs, pallets/phala/src/mock.rs, pallets/phala/src/stakepool.rs, standalone/runtime/src/lib.rs
Fixes #334 
- `PoolInfo::releasing_stake` to account the releasing stake due to force shutdown
- Shut down a pool by force if releasing_stake cannot cover the request after the grace period
- (Accurately) predict the stake return and slashed amount when stopping a miner
=> Correctly apply withdraw grace period

Cargo.lock, pallets/bridge_transfer/src/mock.rs, pallets/phala/src/mock.rs, pallets/phala/src/mq.rs, pallets/phala/src/mq/check_seq.rs, pallets/phala/src/stakepool.rs, standalone/node/Cargo.toml, standalone/node/src/service.rs, standalone/runtime/src/lib.rs
Fixes #232 
This change will introduce a new `SignedExtension` called `CheckMqSequence`. It does two things:
1. Reject any message with its sequence lower than expected early (from being included to a mempool or broadcasted to the p2p network)
2. Keep all the messages from the same sender in a topological order in the mempool, and only include the expected messages in block
This change will ensure no gas burning for redundant or out-of-order messages. Companion changes in `pherry` may be necessary to protect it from crashing when syncing redundant messages.
Note that in principle we should add the corresponding logic of a `SignedExtension` to all the Substrate clients (i.e. Polkadot.js, subxt). However since `CheckMqSequence` doesn't attach any data to a transaction, it can be treated as …
=> chain: introduce CheckMqSequence to manage mempool

.github/actions/install_toolchain/action.yml, .github/workflows/build.yml
This PR tries to deliver #58: Enable E2E test in CI
What this PR achieves:
1. Compiling `pruntime` by Github Actions.
2. Run E2E Testing in Github Actions.
3. Paralleling building and testing to minimize the execution time. Currently there are in total 4 jobs implemented: `build-core-blockchain`, `build-pruntime`, `cargo-test` and `e2e-test`, where the first 3 jobs will be executed in parallel and the `e2e-test` task will be executed after finishing `build-core-blockchain` and `build-pruntime` jobs.
What this PR lacks:
While this PR has all necessary configurations for CI to compile and test (e.g. link shared library, add environment variables, handle artifacts exchanging, etc.), currently this workflow will likely to be fail due to some type errors in `e2e/tests/typeoverride.js` as …
=> Integrate pruntime compiling and e2e testing for CI

standalone/pherry/src/chain_client.rs, standalone/pherry/src/main.rs, standalone/pherry/src/msg_sync.rs, subxt/src/frame/system.rs, subxt/src/lib.rs, subxt/src/rpc.rs
Fixes #378 
- Add `system_accountNextIndex` rpc to subxt
- Read nonce from txpool instead of managing an increasing series
Tested: e2e, testnet
In the past design, `pherry` always track the nonce of the sender account locally. Everytime tie send a transaction, the nonce increases. However this assumes all the transaction will be eventually included in a block. This is not always guaranteed, and it's especially bad after #372.
So in this PR, we read the next nonce from the full node txpool instead. The full node always returns the best next nonce to use. We do this all the time before we want to send transactions.
Note that is has to be handled carefully. The next nonce returned by the full node can be higher than the actual good nonce. An example is that we send the same message …
=> Properly manage account nonce

standalone/pherry/src/pruntime_client.rs
To suppress the log in pRuntime:
```
[2021-08-15T05:39:07Z DEBUG hyper::server] ioerror in keepalive loop = Custom { kind: UnexpectedEof, error: "end of stream before headers finished" }
```
=> pherry: Add HTTP header "Connection: close"

pallets/phala/src/mining.rs
Otherwise, The worker might commit tons of heartbeat messages when it recover to online.
=> pallet-mining: notify the worker Unresponsive

.gitmodules, standalone/pruntime/enclave/Cargo.toml, standalone/pruntime/enclave/src/lib.rs, standalone/pruntime/enclave/src/prpc_service.rs
Crash reason: Illegel instruction CPUID.
rand::thread_rng implementation will use CPUID the detect the CPU features.
it's deps graph:
enclave -> ... -> rand::thread_rng -> rand_chacha -> ppv-lite86 -> std::is_x86_feature_detected -> CPUID.
So we patch ppv-lite86 to use `sgx_trts::is_x86_feature_detected`.
There might be more codes are using std::is_x86_feature_detected. Let’s test and see whether the problem solved.
----
Update:
There are currently two other places depending on `std::is_x86_feature_detected`.
- contract web3analytics
- env_logger
Both due to the usage of `regex`.
`web3analytics` will be ported to wasm in the future, we can disable it currently.
`env_logger `works fine currently, it won't break unless we let it filter log by regex.
----
Update 2:
- the web3analytics is …
=> Patch ppv-lite86 to avoid detect SIMD with CPUID

pallets/bridge/src/lib.rs, scripts/js/src/filterBridgeEvents.js
Introduce custom event storage  to save bridge transfer events of every block, thus on relayer side, we don't need to decode events that not relevant with bridge. This could save us a lot of work to adopt new event types once upstream(substrate) was updated.
=> bridge: add extra storage to save transfer events

pallets/phala/src/mining.rs
Distinguish duplicated miner / worker when binding
=> mining: clearer dup binding error message

Cargo.lock, subxt/Cargo.toml, subxt/client/Cargo.toml, subxt/client/src/lib.rs, subxt/src/error.rs, subxt/src/lib.rs
Port https://github.com/paritytech/substrate-subxt/pull/289 to our fork, Substrate itself already use 0.3.0 for long time, this helps remove old jsonrpsee dependency
=> Port Subxt jsonrpsee 0.3.0 upgrade

crates/phactory/src/system/gk.rs, crates/phala-types/src/lib.rs
Let remember the operation order this time:
1. Upgrade GKs' pruntime.
2. Then send RepairV message after **ALL** GKs get upgraded.
Otherwise the GKs will run into inconsistent state which is a disaster.
=> gk: implement Repair V

standalone/pruntime/enclave/Enclave.config.dev.xml, standalone/pruntime/enclave/Enclave.config.prod.xml
Stack size:  64MB x 32 -> 8MB x 32
Heap size:  256MB -> 1024MB
Total: 2304MB -> 1280MB
The default app stack size of most linux desktop distribution is 8MB, some embed system is 2MB. The stack size of linux kernel threads is 16**KB**.
So 8MB of stack size is adequate for most real world applications. There is no stack cost codes in our app.
We already have encountered OOM when sync header with batch size of 1000. So the current heap size would be not enough for future business.
=> enclave: Adjust heap & stack size

Cargo.lock, Cargo.toml, crates/phactory/pal/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phala-allocator/Cargo.toml, crates/phala-allocator/src/lib.rs, standalone/pruntime/enclave/Cargo.lock, standalone/pruntime/enclave/Cargo.toml, standalone/pruntime/enclave/src/pal_sgx.rs
Currently, It statistics the global heap usage and peak usage in `Rust` with an custom Rust Allocator.
Anthor bonus is the `g_peak_heap_used` export by sgx-sdk providing the global enclave heap peak usage.
=> enclave: Add memory usage stats

Cargo.lock, pallets/phala/Cargo.toml, pallets/phala/src/lib.rs, pallets/phala/src/stakepool.rs, pallets/phala/src/stakepool/migrations.rs, standalone/runtime/Cargo.toml
Fixes #487 
- Handle dust when calculating stake & shares in the following rules:
- Dust in user's locked stake will be removed by slash
- Dust in a user's share is removed, and always maintain the invariant: sum(user shares) == pool's total share
- Dust in a pool's total_stake is removed
- Dust in withdraw queue is removed
- Dust in payout report from GK is dismissed
- Add a migration to remove all the existing dust in the storage
- Analyzed with `try_runtime`, and with state dumped for offline analysis
Unit test with grcov:
=> Fix #487: remove dust in stake & share calc

pallets/phala/src/mining.rs, pallets/phala/src/mock.rs, pallets/phala/src/stakepool.rs, standalone/runtime/src/lib.rs
Partially fixes #500 
The root case of the issue is that some functions doesn't check the existing storage before inserting a new value, causing unexpected overwriting.
=> Check worker status before start mining

crates/phactory/src/contracts/mod.rs, crates/phactory/src/contracts/pink.rs, crates/phactory/src/light_validation/mod.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/secret_channel.rs, crates/phactory/src/side_task.rs, crates/phactory/src/system/gk.rs, crates/phactory/src/system/side_tasks/geo_probe.rs, crates/phala-mq/Cargo.toml, crates/phala-mq/src/lib.rs, crates/phala-mq/src/send_queue.rs, crates/phala-mq/src/types.rs, crates/phala-mq/tests/tests.rs, crates/phala-types/src/lib.rs
The previous side task implementation did not consider pRuntime snapshoting. This PR fixes it. 
Major changes:
- Refactor phala-mq to be able to make SigningMessage without giving it a sequence and without pushing it into the queue.
- Better secret channel API. Now it impl phala_mq::traits::MessageChannel as well. 
- Refactor the side-task.
-  Constraint the number of mq messages it emits.
-  To be snapshot friendly, default messages must be supplied when adding new side-tasks. The default messages are replacement when the async task does not finish successfully and can be stored in the pRuntime snapshot.
-  Simplify the async task API, check the [new demo](https://github.com/Phala-Network/phala-blockchain/commit/side-task-demo3).
=> Refactor the side task

pallets/phala/src/stakepool.rs
Fixes #527
In `remove_stake()`, the PHA amount to remove is calculated on-the-fly based on the share and the share price. It introduces the precision problem. Even the share doesn't exceed the user's share, the calculated amount can be a little bit higher than both `pool.free_stake` and `user.locked`. We didn't check the later case. As a result, it may cause a panic in the downstream code.
=> Cap the removing stake by user locked amount

scripts/js/bugfix-tools/b500-check-fix-compete.js, scripts/js/bugfix-tools/b500-check-post-missing.js, scripts/js/bugfix-tools/b500-dump-events.js, scripts/js/bugfix-tools/b500-gen-reconcile.js, scripts/js/bugfix-tools/b500-preprocess.js, scripts/js/bugfix-tools/b500-reconstruct-error.js, scripts/js/src/utils/palletUtils.js
1. Prepare a Khala Network archive full node
2. Init the js script project by `yarn` under `scripts/js`
3. Dump all the related mining events
```bash
node ./bugfix-tools/b500-dump-events.js
node ./bugfix-tools/b500-preprocess.js
```
- Optionally, specify the ws api port by env var `ENDPOINT`
- It will create some json files under `./tmp` directory as the input for the next step. Make a directory if it doesn't exist.
4. Find out the affected miners
```bash
node ./bugfix-tools/b500-reconstruct-error.js
```
5. Double check if the generated data with the affected miners is correct.
```bash
node bugfix-tools/b500-check-fix-compete.js
```
- It compares the sum of the stake of all the miners in CD state with sum of the `releasingStake` in all the pools. Please note that because of #541, the two …
=> Backfill scripts to fix #500 

standalone/pherry/Cargo.toml, standalone/pherry/src/lib.rs, standalone/pherry/src/msg_sync.rs
and optional other tx errors.
The first commit is a trivial refactor. Pay your review attention on the second commit.
=> pherry: restart on bad signature

scripts/dump-metadata.py
Usage:
```
$ ./dump-metadata.py -h
usage: dump-metadata.py [-h] [--url URL] [output]
Dump metadata from a running substrate node
positional arguments:
output      output file
optional arguments:
-h, --help  show this help message and exit
--url URL   HTTP RPC address of the substrate node
```
Example:
```bash
$ ./dump-metadata.py --url http://localhost:9933 kusama_metadata.scale
$ ./dump-metadata.py --url http://localhost:9934 khala_metadata.scale
$ ll kusama_metadata.scale 
-rw-rw-r-- 1 kvin kvin 146284 11月 25 09:55 kusama_metadata.scale
```
=> Add script to dump metadata

Cargo.lock, crates/pink/pink-extension/macro/src/lib.rs, crates/pink/pink-extension/src/lib.rs, pallets/bridge_transfer/src/tests.rs, pallets/phala/src/ott.rs, pallets/phala/src/stakepool.rs, pallets/utility/Cargo.toml, pallets/utility/src/lib.rs, pallets/utility/src/tests.rs, standalone/node/Cargo.toml, standalone/pruntime/app/Cargo.lock, standalone/pruntime/enclave/Cargo.lock, standalone/runtime/Cargo.toml
Polkadot v0.9.13 rebased to latest Substrate, this follow it and fix compiling error
Ref:
- https://github.com/paritytech/ink/pull/665/files#diff-566cb62a6fb39478a16519af9ca70b3d903c02ec644223f5bf0c9e531e629d8dR69
- https://github.com/paritytech/ink/pull/1036
- https://github.com/paritytech/substrate/pull/9993
Note:
```
test running_the_node_works_and_can_be_interrupted ... FAILED
test running_two_nodes_with_the_same_ws_port_should_work ... FAILED
failures:
---- running_the_node_works_and_can_be_interrupted stdout ----
thread 'running_the_node_works_and_can_be_interrupted' panicked at 'called `Result::unwrap()` on an `Err` value: Elapsed(())', standalone/node/tests/running_the_node_and_interrupt.rs:48:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- …
```
=> Update to latest Substrate 

.gitmodules, standalone/pruntime/enclave/Cargo.lock, standalone/pruntime/enclave/Cargo.toml
This PR rollback futures-rs-0.3.18 to 0.3.17 since the 18 has been [yanked](https://crates.io/crates/futures-core/versions) on crates.io.
Also add feature gates for all patched crates so that those patches do not take effects on proc-macro or build dependencies.
=> pRuntime: Rollback futures-rs from 0.3.18 to 0.3.17

standalone/pruntime/enclave/build.rs
The top Makefile takes care of it well.
=> enclave: Dont link to sgx_tprotected_fs

crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, standalone/pherry/src/lib.rs, standalone/pruntime/enclave/src/pal_sgx.rs, standalone/pruntime/pruntime/src/ra.rs
This PR improve the previous weird error messages like:
```
[2022-02-15T09:56:22Z INFO  pherry] bridge() exited with error: Seal runtime data
```
changes to
```
[2022-02-15T10:18:41Z INFO  pherry] bridge() exited with error: Failed to seal runtime data
Caused by:
No such file or directory (os error 2)
```
=> Better error messages

crates/pink/pink-extension/macro/src/lib.rs, crates/pink/pink-extension/src/chain_extension.rs, crates/pink/pink-extension/src/chain_extension/signing.rs, crates/pink/src/runtime/extension.rs
This PR add a attribute_macro `chain_extension` as a drop-in replacement of `ink_lang::chain_extension`.
The macro generates some extra codes:
- A trait `PinkExtBackend` for the runtime to implement.
- Const variables for the function ids.
- A call dispatcher
With this improvement, the runtime now implements the extension functions more type-safe.
=> Improvements of chain extension implementation

Cargo.lock, standalone/replay/Cargo.toml, standalone/replay/src/replay_gk/data_persist.rs, standalone/replay/src/replay_gk/httpserver.rs
=> gk-replay: add "/workers" to dump the full list

crates/pink/src/runtime.rs
limit the wasm code size to 2MB max limit
=> Add the contract code size limit 

crates/pink/examples/http_client/lib.rs, crates/pink/pink-extension/macro/src/lib.rs, crates/pink/pink-extension/src/chain_extension/test.rs
Let the attribute macro `chain_extension` also generate mock helper functions:
```rust
pub fn mock_http_request(call: impl FnMut(HttpRequest) -> HttpResponse + 'static) {
ink_env::test::register_chain_extension(MockExtension::<_, _, _, 4278190081>::new(
call,
));
}
pub fn mock_sign(call: impl FnMut(SignArgs) -> Vec<u8> + 'static) {
ink_env::test::register_chain_extension(MockExtension::<_, _, _, 4278190082>::new(
call,
));
}
pub fn mock_verify(call: impl FnMut(VerifyArgs) -> bool + 'static) {
ink_env::test::register_chain_extension(MockExtension::<_, _, _, 4278190083>::new(
call,
));
}
pub fn mock_derive_sr25519_key(call: impl FnMut(Cow<[u8]>) -> Vec<u8> + 'static) {
ink_env::test::register_chain_extension(MockExtension::<_, _, _, 4278190084>::new(
call,
));
}
pub fn …
```
=> pink-macro: generate mock helper

crates/phactory/Cargo.toml, crates/phactory/src/contracts/assets.rs, crates/phactory/src/contracts/balances.rs, crates/phactory/src/contracts/btc_lottery.rs, crates/phactory/src/contracts/btc_price_bot.rs, crates/phactory/src/contracts/data_plaza.rs, crates/phactory/src/contracts/geolocation.rs, crates/phactory/src/contracts/guess_number.rs, crates/phactory/src/contracts/mod.rs, crates/phactory/src/contracts/pink.rs, crates/phactory/src/contracts/support.rs, crates/phactory/src/contracts/support/keeper.rs, crates/phactory/src/contracts/web3analytics.rs, crates/phactory/src/cryptography/aead.rs, crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/system/mod.rs, crates/phala-trie-storage/src/lib.rs, crates/pink/src/contract.rs, crates/pink/src/lib.rs, crates/pink/src/storage.rs, crates/pink/src/storage/backend.rs, standalone/pruntime/enclave/src/lib.rs, standalone/pruntime/pruntime/Cargo.lock, standalone/pruntime/pruntime/src/runtime.rs
This PR add support for concurrent query for pruntime.
The previous implementation required locking the global Phactory instance to handle any pRPC request. This PR tuned the architecture to let the inner pRPC implementation to deside to whether to lock the global instance.
And further more splited the query RPC into two parts, the bottom-half could be executed after the lock has been released.
This requires the contracts and storage to be able to take snapshot on their states. **The snapshots are currently implemented with simple clone and should be optimized to in some lightweight way in the future**.
=> Concurrent query

crates/phactory/Cargo.toml
@h4x3rotab please check. It should not break anything else.
=> Fix CVE-2022-24713 regex vulnerability

crates/phactory/api/Cargo.toml, crates/phactory/api/src/blocks.rs, crates/phactory/api/tests/snapshots/test_block_abi__sync_blocks_abi_should_not_change-2.snap, crates/phactory/api/tests/snapshots/test_block_abi__sync_blocks_abi_should_not_change-3.snap, crates/phactory/api/tests/snapshots/test_block_abi__sync_blocks_abi_should_not_change-4.snap, crates/phactory/api/tests/snapshots/test_block_abi__sync_blocks_abi_should_not_change.snap, crates/phactory/api/tests/test_block_abi.rs, crates/phala-trie-storage/Cargo.toml, crates/phala-trie-storage/src/ser.rs
This PR use TypeInfo to detect if there are any type definition changes in block header when we upgrade substrate. So that we can know if the old version of pruntime is compatible with new version of chain.
=> Add tests to detect block ABI changes

pallets/phala/src/mining.rs, pallets/phala/src/stakepool.rs
Fixes #692
This enables miners to restart mining as long as the new stake is greater
than the old stake. Also useful to reset the benchmark score after a bad
performance test.
- Completely disable slash
- Reject late settlement from GK after V is updated (i.e. a restart)
- Implement restart mining logic
Tested: unit test & coverage
=> Restart mining

crates/phactory/src/prpc_service.rs, standalone/pherry/src/lib.rs
@jasl Can you test this PR? I haven't test it yet.
To test:
To do:
=> pruntime: Allow to reset operator in GetRuntimeInfo

crates/phactory/src/contracts/mod.rs, crates/phactory/src/contracts/pink.rs, crates/phactory/src/contracts/support.rs, crates/phactory/src/contracts/support/keeper.rs, crates/phactory/src/system/mod.rs
This PR removed the abstraction over native/wasm. The top level `trait Contract` is removed. Instead, a new type `struct FatContract` is Introduced. Removed generic type parameters on those contract types. Reduced Contract type structural layers.
This make the code much easier to be understood.
#699 need to rebase onto this work.
=> Refactor the fat contract.

standalone/pruntime/app/src/main.rs
Fixes #724
The `/kick` API hangs because the `destroy_enclave` would block if there are any threads called into the enclave and we have benchmark threads always running if the worker is mining.
We simplely remove the destroying and let the OS clean it up.
=> pruntime: Fix hanging on kick

standalone/replay/src/replay_gk/data_persist.rs
This PR allows the replayer to override dirty data. Sometimes if we run an incorrect version of replayer, it may write bad data to the db. In such case, we can manually remove the bad data an rerun GK replay. However, without this PR, the write the db will be batched, and some rows at the edge may conflict with the data left in the db, and causing the full batch to fail to write. With this PR, the write will always override the rows in the database.
=> replay: upsert to db

crates/phactory/Cargo.toml, crates/phactory/api/src/ecall_args.rs, crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, standalone/pruntime/pruntime/gramine-build/pruntime.manifest.template, standalone/pruntime/pruntime/src/api_server.rs, standalone/pruntime/pruntime/src/main.rs, standalone/pruntime/pruntime/src/pal_gramine.rs, standalone/pruntime/pruntime/src/runtime.rs
This PR implement auto taking checkpoints for gramine based pruntime.
Instead of write to tempfile then rename, we append block number to the filename to get rid of power cut off on writing file.
By default, keep latest 5 checkpoints:
```
ll data/
total 9712
drwxrwxr-x 2 kvin kvin    4096 4月  19 16:27 ./
drwxrwxr-x 6 kvin kvin    4096 4月  19 10:51 ../
-rw-rw-r-- 1 kvin kvin 1983963 4月  19 16:27 checkpoint.seal-000000570
-rw-rw-r-- 1 kvin kvin 1984253 4月  19 16:27 checkpoint.seal-000000572
-rw-rw-r-- 1 kvin kvin 1985183 4月  19 16:27 checkpoint.seal-000000574
-rw-rw-r-- 1 kvin kvin 1985268 4月  19 16:27 checkpoint.seal-000000577
-rw-rw-r-- 1 kvin kvin 1985686 4月  19 16:27 checkpoint.seal-000000579
-rw-rw-r-- 1 kvin kvin      98 4月  19 16:24 runtime-data.seal
```
@jasl  A new option …
=> Auto take checkpoints for gramine based pRuntime

scripts/debug-cli/Cargo.toml, scripts/debug-cli/src/main.rs, standalone/pherry/Cargo.toml, standalone/pherry/src/lib.rs, standalone/pruntime/pruntime/Cargo.toml, standalone/pruntime/pruntime/src/main.rs, standalone/replay/Cargo.toml, standalone/replay/src/main.rs
Since structopt was merged into latest clap.
Bonus: The help messages now keep in it's declared order.
Before:
```
pruntime 0.1.0
The Phala TEE worker app.
USAGE:
pruntime [FLAGS] [OPTIONS]
FLAGS:
--allow-cors                     Allow CORS for HTTP
--disable-checkpoint             Disable checkpoint
--enable-kick-api                Turn on /kick API
-h, --help                           Prints help information
--init-bench                     Run benchmark at startup
--remove-corrupted-checkpoint    Remove corrupted checkpoint so that pruntime can restart to continue to load
others
-V, --version                        Prints version information
OPTIONS:
--address <address>                              Listening IP address of HTTP
--checkpoint-interval <checkpoint-interval>
Checkpoint …
```
=> Use clap instead of structopt

Cargo.lock, crates/pink/Cargo.toml, pallets/utility/src/tests.rs, standalone/node/Cargo.toml, standalone/node/build.rs, standalone/node/src/cli.rs, standalone/node/src/command.rs, standalone/node/src/command_helper.rs, standalone/node/src/lib.rs, standalone/pruntime/app/Cargo.lock, standalone/pruntime/enclave/Cargo.lock, standalone/pruntime/pruntime/Cargo.lock, standalone/replay/Cargo.toml, standalone/replay/src/replay_gk.rs, standalone/replay/src/replay_gk/httpserver.rs, standalone/runtime/src/lib.rs
- Update to prior Polkadot 0.9.19
- Update actix 4 for GK replay (fixes #723)
- Switch to Rust edition 2021 for PInk
=> Upgrade to prior Polkadot 0.9.19

Cargo.lock, Cargo.toml, crates/phala-rocket-middleware/Cargo.toml, crates/phala-rocket-middleware/src/lib.rs, crates/phala-rocket-middleware/src/time_meter.rs, standalone/pruntime/Cargo.toml, standalone/pruntime/src/api_server.rs, standalone/pruntime/src/main.rs
New command line argument:
```
--measure-rpc-time
Measuring the time it takes to process each RPC call
```
This would mount the meter middleware onto rocket server. That would print log like:
```
[2022-04-25T07:20:31Z INFO  measuring] GET /get_info cost 886 micro seconds
```
And a header in the HTTP response:
```
HTTP/1.1 200 OK
X-Cost-Time: 886
```
=> pruntime: Add option to measure time cost of each RPC

crates/phactory/api/src/storage_sync.rs, crates/phactory/src/prpc_service.rs
=> Don't overwrite the last state_root if given headers is empty

Cargo.lock, Cargo.toml, crates/pink/sidevm/examples/host/Cargo.toml, crates/pink/sidevm/examples/httpserver/Cargo.toml, crates/pink/sidevm/examples/recv_messages/Cargo.toml, crates/pink/sidevm/examples/timer/Cargo.toml
Exclude those examples because they don't compile under macOS due to undefined `sidevm_ocall` and `sidevm_ocall_fastreturn`.
We can resolve the compilation error by marking the two functions as `extern_weak` once the Rust [linkage](https://github.com/rust-lang/rust/issues/29603) feature being stablized.
This fixes #762.
=> Exclude sidevm examples from the workspace

Cargo.lock, crates/phala-rocket-middleware/Cargo.toml, crates/phala-rocket-middleware/src/time_meter.rs, e2e/src/fullstack.js, standalone/pruntime/Cargo.lock, standalone/pruntime/Cargo.toml, standalone/pruntime/gramine-build/Rocket.toml, standalone/pruntime/gramine-build/pruntime.manifest.template, standalone/pruntime/src/api_server.rs, standalone/pruntime/src/main.rs
Prb want the `keep-alive` feature but the rocket 0.4.x has a bug which would force close the connections even when the `keep-alive` is turned on.
See https://rocket.rs/master/guide/upgrading-from-0.4/#configuration
=> Update rocket to 0.5-rc.1

Cargo.lock, crates/phala-node-rpc-ext/Cargo.toml, crates/phala-node-rpc-ext/src/storage_changes.rs
Tested with https://github.com/Phala-Network/phala-blockchain/pull/770, it can get about 1k blocks/sec from `phala-node --dev` on the AMD EPYC machine.
=> node-rpc: Boost the speed of get_storages_changes with rayon

Cargo.lock, crates/phactory/api/Cargo.toml, crates/phactory/api/src/ecall_args.rs, crates/phactory/api/src/storage_sync.rs, crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phala-trie-storage/src/lib.rs, crates/phaxt/src/lib.rs, standalone/headers-cache/Cargo.toml, standalone/headers-cache/README.md, standalone/headers-cache/src/db.rs, standalone/headers-cache/src/main.rs, standalone/headers-cache/src/web_api.rs, standalone/pherry/src/chain_client.rs, standalone/pherry/src/headers_cache.rs, standalone/pherry/src/lib.rs, standalone/pherry/src/prefetcher.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/src/main.rs, standalone/replay/src/replay_gk.rs
Two main features were added in this PR.
- The size of khala headers at the moment is 285M. So it's cheap to add them to the cache server. And can help (not much) on parachain headers fetching speed by batch fetching.
- The size of all storage changes is about 64GB. it could significantly improve the syncing speed if we cache them. 
When syncing storages, pherry first fetches a batch of storage changes from the chain and then sends them into pRuntime. Both the 2 steps cost some time. 
In this PR, pherry prefetches the next batch of `changes` while sending the current batch to the pRuntime, simultaneously.
Default to 100 blocks
=> More pherry sync speed improvements

Cargo.lock, Cargo.toml, crates/phactory/api/Cargo.toml, crates/phactory/api/src/blocks.rs, crates/phactory/api/src/ecall_args.rs, crates/phactory/api/src/storage_sync.rs, crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phala-trie-storage/src/lib.rs, crates/phaxt/src/lib.rs, standalone/headers-cache/Cargo.toml, standalone/headers-cache/README.md, standalone/headers-cache/src/db.rs, standalone/headers-cache/src/main.rs, standalone/headers-cache/src/web_api.rs, standalone/pherry/src/chain_client.rs, standalone/pherry/src/headers_cache.rs, standalone/pherry/src/lib.rs, standalone/pherry/src/prefetcher.rs, standalone/pherry/src/types.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/src/main.rs, standalone/replay/src/replay_gk.rs
This PR introduce a new cache server component named `headers-cache`.
And pherry now can fetch relaychain headers from `headers-cache`. 
With this cache, miners can turn off the `--archive` of their kusama nodes.
```
headers-cache grab genesis --from-block <number> genesis.bin
headers-cache grab headers --from-block <number> headers.bin
```
```
killall headers-cache
headers-cache import genesis genesis.bin
headers-cache import headers headers.bin
```
```
ROCKET_PORT=8002 headers-cache serve
```
```
pherry ... --headers-cache-uri http://localhost:8002
```
Parachain headers and storage changes can also be cached in `headers-cache` (by #773)
```
headers-cache grab para-headers --from-block <number> para-headers.bin
headers-cache import para-headers para-headers.bin
```
```
headers-cache grab …
```
=> Kusama headers cache server for pherry

Cargo.lock, crates/pink/pink-extension/Cargo.toml, crates/pink/pink-extension/src/chain_extension/test.rs
Ink! has changed its mocking input codec ABI in 3.0.0.
=> pink-extension: Fix extension mocking codec error

standalone/headers-cache/src/db.rs, standalone/headers-cache/src/main.rs, standalone/headers-cache/src/web_api.rs
Unlike the leveldb-rs, rocksdb doesn't require `&mut self` to access the DB. So let's peel the `Mutex` away.
This may make it faster when multiple pherrys connect to a single cache server.
=> headers-cache: Lock-free DB accessing

crates/pink/sidevm/env/src/lib.rs, crates/pink/sidevm/env/src/ocall_def.rs, crates/pink/sidevm/host-runtime/src/env.rs, crates/pink/sidevm/host-runtime/src/resource.rs, crates/pink/sidevm/sidevm/src/channel.rs, crates/pink/sidevm/sidevm/src/net.rs, crates/pink/sidevm/sidevm/src/time.rs
This makes the ocalls simpler and easier to turn more types to support fast io.
=> sidevm ocall: Flatten the Result<Poll<T>> into Result<T>

Cargo.lock, standalone/headers-cache/Cargo.toml, standalone/headers-cache/src/db.rs, standalone/headers-cache/src/main.rs
```bash
$ ./headers-cache inspect-db
{
"genesis": [
8325311
],
"recent_imported": {
"header": 8346148,
"para_header": 1573035,
"storage_changes": null
},
"higest": {
"header": 8756226,
"para_header": 1573035,
"storage_changes": null
}
}
$ ./headers-cache inspect-db | jq .higest.header
8756226
```
=> headers-cache: Inspect block numbers in cache DB

standalone/pruntime/src/main.rs
This is a better solution than falling back to the behavior of `rocket 0.4`. Because it can still gracefully wait for the ongoing taking checkpoint progress to complete.
=> pruntime: Don't wait for other threads while rocket exited

crates/phactory/api/src/ecall_args.rs, crates/phactory/src/lib.rs, standalone/pruntime/app/src/main.rs, standalone/pruntime/enclave/src/lib.rs
And removed the previous option `--skip-corrupted-checkpoint` since it is not safe.
This fixes #727
=> pruntime: add option "--remove-corrupted-checkpoint"

Cargo.lock, crates/pink/examples/start_sidevm/sideprog/Cargo.toml, crates/pink/examples/start_sidevm/sideprog/src/lib.rs, crates/pink/sidevm/env/Cargo.toml, crates/pink/sidevm/env/src/lib.rs, crates/pink/sidevm/env/src/tasks.rs, crates/pink/sidevm/examples/host/Cargo.toml, crates/pink/sidevm/examples/host/src/main.rs, crates/pink/sidevm/examples/httpserver/Cargo.toml, crates/pink/sidevm/examples/httpserver/src/lib.rs, crates/pink/sidevm/examples/tcpclient/Cargo.lock, crates/pink/sidevm/examples/tcpclient/Cargo.toml, crates/pink/sidevm/examples/tcpclient/src/lib.rs, crates/pink/sidevm/host-runtime/Cargo.toml, crates/pink/sidevm/host-runtime/src/instrument.rs, crates/pink/sidevm/host-runtime/src/run.rs, crates/pink/sidevm/logger/Cargo.toml, crates/pink/sidevm/macro/Cargo.toml, crates/pink/sidevm/sidevm/Cargo.toml, crates/pink/sidevm/sidevm/src/lib.rs, crates/pink/sidevm/sidevm/src/net.rs, crates/pink/sidevm/sidevm/src/time.rs, crates/rustfmt-snippet/Cargo.toml
This PR implements some improvements:
- Implement `futures::io::{AsyncRead, AsyncWrite}` as well as the ones in `tokio` for `sidevm::net::TcpStream`.
The `futures::*` is preferred because the authors always design them with `runtime-agnostic` in mind.
- Support joining on the task handle.
We can now write things like: 
```rust
let handle = sidevm::spawn(async { ... });
let _ = handle.await;
```
- Add util fn `sidevm::time::timeout(future)`.
- Support instrumenting for float instructions.
- Publish crates to `crates.io`.
=> Sidevm improvements

Cargo.lock, crates/pink/examples/start_sidevm/sideprog/Cargo.toml, crates/pink/examples/start_sidevm/sideprog/src/lib.rs, crates/pink/sidevm/env/Cargo.toml, crates/pink/sidevm/env/src/lib.rs, crates/pink/sidevm/env/src/ocall_def.rs, crates/pink/sidevm/env/src/tasks.rs, crates/pink/sidevm/examples/host/Cargo.toml, crates/pink/sidevm/examples/host/src/main.rs, crates/pink/sidevm/examples/httpserver/Cargo.toml, crates/pink/sidevm/examples/httpserver/src/lib.rs, crates/pink/sidevm/examples/tcpclient/Cargo.lock, crates/pink/sidevm/examples/tcpclient/Cargo.toml, crates/pink/sidevm/examples/tcpclient/src/lib.rs, crates/pink/sidevm/examples/timer/Cargo.toml, crates/pink/sidevm/examples/timer/src/lib.rs, crates/pink/sidevm/host-runtime/Cargo.toml, crates/pink/sidevm/host-runtime/src/async_context.rs, crates/pink/sidevm/host-runtime/src/env.rs, crates/pink/sidevm/host-runtime/src/instrument.rs, crates/pink/sidevm/host-runtime/src/resource.rs, crates/pink/sidevm/host-runtime/src/run.rs, crates/pink/sidevm/logger/Cargo.toml, crates/pink/sidevm/macro/Cargo.toml, crates/pink/sidevm/sidevm/Cargo.toml, crates/pink/sidevm/sidevm/src/channel.rs, crates/pink/sidevm/sidevm/src/lib.rs, crates/pink/sidevm/sidevm/src/net.rs, crates/pink/sidevm/sidevm/src/time.rs, crates/rustfmt-snippet/Cargo.toml
This enables the `futures-channel` to work in sidevm. And enables some other stuff like `FuturesUnordered` from the crate `futures`.
An `async channel` is a hard requirement for inter-task communication. There are some implementations with different requirements in the ecosystem:
- tokio-channel: depends on the tokio runtime which can not be used in sidevm.
- futures-channel: uses the Waker from the poll Context.
- async-channel(from the async-std team): I haven't looked into it yet. But it must at least require access to the Waker.
=> sidevm: Implement guest space waker

Cargo.lock, crates/pink/src/runtime.rs, pallets/bridge/src/lib.rs, pallets/bridge/src/mock.rs, pallets/bridge_transfer/src/mock.rs, pallets/kitties/src/lib.rs, pallets/phala/src/mining.rs, scripts/debug-cli/src/main.rs, standalone/pruntime/Cargo.lock, standalone/rpc/Cargo.toml, standalone/rpc/src/lib.rs, standalone/runtime/src/impls.rs, standalone/runtime/src/lib.rs
https://github.com/paritytech/substrate/compare/polkadot-v0.9.22...polkadot-v0.9.23
Some notable changes:
- https://github.com/paritytech/substrate/pull/11414
- https://github.com/paritytech/substrate/pull/10719
=> Upgrade to Polkadot 0.9.23

Cargo.lock, crates/phala-trie-storage/Cargo.toml, crates/phala-trie-storage/src/lib.rs, crates/phala-trie-storage/src/memdb.rs, crates/pink/Cargo.toml, crates/pink/src/contract.rs, crates/pink/src/storage.rs, crates/pink/tests/test_pink_contract.rs, standalone/pruntime/Cargo.lock
The enables lightweight snapshots for cluster storage.
=> pruntime: Use im::HashMap as trie storage backend

Cargo.lock, Cargo.toml, crates/phactory/src/system/mod.rs, crates/pink/Cargo.toml, crates/pink/sidevm/host-runtime/Cargo.toml, crates/pink/sidevm/host-runtime/src/env.rs, crates/pink/src/runtime/extension.rs, crates/reqwest-proxy/Cargo.toml, crates/reqwest-proxy/src/lib.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/Cargo.toml, standalone/pruntime/gramine-build/pruntime.manifest.template, standalone/pruntime/src/ra.rs
After doing some research, I find it not easy to transparently proxy the pruntime outgoing connections. The techniques like the [proxychains](https://github.com/rofl0r/proxychains-ng) do not work with gramine-sgx. It is also easy to make mistakes if we use iptables to redirect outgoing TCP connections.
So the easier way would be the pruntime with built-in sock5 proxy support.
This PR adds built-in socks5 proxy support. A proxy server is configured via the `all_proxy` env var. `socks5://` and `socks5h://` are supported. The later also sending DNS queries via the proxy server.
example:
```
all_proxy=socks5h://localhost:1080 ./pruntime
```
We can also set `i2p_proxy` for domains ending with `.i2p`:
```
i2p_proxy=socks5h://localhost:4447 all_proxy=socks5h://localhost:1080 ./pruntime
```
The …
=> pruntime: Support socks5 proxy for outgoing tcp connections

crates/phactory/pal/src/lib.rs, crates/phactory/src/lib.rs, crates/phactory/src/secret_channel.rs, crates/phactory/src/system/mod.rs, crates/phala-mq/src/dispatcher.rs, crates/phala-mq/src/types.rs, crates/phala-types/src/lib.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/Cargo.toml, standalone/pruntime/src/pal_gramine.rs
Main changes in this PR:
- Add the MQ event PRuntimeManagementEvent, which is used to retire pRuntimes explicitly.
- Abort when pruntime failed to decode a message from a trusted origin.
=> Support to kick old pruntime

standalone/pherry/src/lib.rs
Too large batch could let the RPC to the node to fail with:
```
The background task been terminated because:
Networking or low-level protocol error:
WebSocket connection error:
message too large: len >= 11443848, maximum = 10485760; restart required
```
=> pherry: Turn down the default block batch size to 4

Cargo.lock, crates/phactory/api/src/ecall_args.rs, crates/phactory/pal/src/lib.rs, crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/system/mod.rs, crates/phala-trie-storage/Cargo.toml, crates/phala-trie-storage/src/lib.rs, crates/phala-trie-storage/src/memdb.rs, crates/pink/sidevm/host-runtime/src/service.rs, e2e/src/fullstack.js, standalone/pruntime/Cargo.lock, standalone/pruntime/gramine-build/Makefile, standalone/pruntime/gramine-build/pruntime.manifest.template, standalone/pruntime/src/main.rs, standalone/pruntime/src/pal_gramine.rs, standalone/pruntime/src/runtime.rs
Main changes in this PR:
- [Encrypt state checkpoint with custom AEAD instead of gramine protected files](https://github.com/Phala-Network/phala-blockchain/pull/838/commits/18ed9c29a5732f8f6a6b60f0afa38db0d2b6de51)
This enables resync-free pruntime upgrading in the future
- [Remove the slow GC in MemoryDB](https://github.com/Phala-Network/phala-blockchain/pull/838/commits/3d1777fd0f5a2498f96c18cc3c40b5275cda4932)
Instead, we remove the value immediately once its ref count goes zero. This makes it possible to sync the pruntime from scratch in `4` hours.
- [Zero overhead MemoryDB ser/de](https://github.com/Phala-Network/phala-blockchain/pull/838/commits/29dec9e722b4d4571fe6d3adb46f4886e46e186f)
In the previous implementation, we collect the key/value pairs into a Vec<(k,v)> before the …
=> pruntime: Some fixes and optimiztions

standalone/pruntime/gramine-build/Makefile
Made `pruntime.token` optional (still eager build by default)
Reason:
- The token is only for EPID, DCAP and no-SGX are not use this
- It's uniqueness that can't share arcross machines, don't generate it on production docker building process can reduce a layer (no longer need an extra delete it step)
=> optional create pruntime.token

crates/pink/pink-extension-runtime/Cargo.toml, dockerfile.d/01_apt_gramine.sh, standalone/pruntime/Cargo.lock, standalone/pruntime/gramine-build/.gitignore, standalone/pruntime/gramine-build/Makefile, standalone/pruntime/gramine-build/gramine-dir, standalone/pruntime/gramine-build/gramine-sgx, standalone/pruntime/gramine-build/pruntime.manifest.template
This makes it easier to run multiple versions of pruntime in a single container.
Self explained steps:
```
cd standalone/pruntime/gramine-build
make run
```
Or
```
cd standalone/pruntime/gramine-build
make dist
cd ../bin
./gramine-sgx pruntime
```
=> gramine-build: Use relative path for files mounted into enclave

Cargo.lock, crates/phactory/Cargo.toml, crates/phala-types/src/lib.rs, crates/pink/sidevm/host-runtime/Cargo.toml, crates/wasmer-tunables/Cargo.toml, standalone/pherry/src/endpoint.rs, standalone/pherry/src/lib.rs, standalone/pruntime/Cargo.lock
This should fix the follow security warnings:
The rest could not be fixed yet.
=> Fix some security alerts and compilation warnings

Cargo.lock, standalone/prouter/Cargo.lock, standalone/pruntime/Cargo.lock
Parity push few new commits to the branch, majorly is libp2p upgrade which said could reduce dependencies
=> Upgrade to Polkadot 0.9.26 again

standalone/pruntime/src/pal_gramine.rs
Add this since the gramine:master support it now
=> pruntime: Report peak memory usage in get_info

crates/phactory/src/contracts/pink.rs, crates/pink/sidevm/env/src/messages.rs
Sorry, I forgot this. That's exactly the purpose of the nonce. It may be used to connect the message output to it's original TX.
=> Send the nonce of Command(InkMessage) to log handler

Cargo.lock, crates/pink/sidevm/env/Cargo.toml, crates/pink/sidevm/env/src/ocall_def.rs, crates/pink/sidevm/env/src/tasks.rs, crates/pink/sidevm/examples/take-a-rest/Cargo.toml, crates/pink/sidevm/examples/take-a-rest/src/lib.rs, crates/pink/sidevm/host-runtime/src/async_context.rs, crates/pink/sidevm/host-runtime/src/env.rs, crates/pink/sidevm/host-runtime/src/run.rs, crates/pink/sidevm/sidevm/Cargo.toml, crates/pink/sidevm/sidevm/src/time.rs
Guest code can call this API regularly to avoid being stifled.
=> sidevm: Add sidevm:time::maybe_rest()

crates/phactory/src/prpc_service.rs, crates/phactory/src/system/gk.rs, crates/phactory/src/system/mod.rs, crates/phala-types/src/lib.rs, standalone/replay/src/replay_gk.rs
Previously, the dispatching order for `phala-mq` was only kept within a `phala_mq::select!` block.
This PR keeps the order globally. 
There might be some performance impacts because the memory accessing would be frequently jumping from one contract to another which is not cache friendly and would cause more EPC page faults.
=> Keep mq dispatching order

standalone/pherry/src/headers_cache.rs, standalone/pherry/src/lib.rs
This fixes the bug reported by Wang Zhe @skysummerice : 
```
[2022-08-27T15:09:25.966576Z INFO  pherry] pRuntime get_info response: PhactoryInfo {
initialized: true,
registered: false,
genesis_block_hash: Some(
"ff93a4a903207ad45af110a3e15f8b66c903a0045f886c528c23fe7064532b08",
),
public_key: Some(
"78aaed50c54bc3912214991ad9b230ad3bc47c88e6504a81b65a4925372ba27f",
),
ecdh_public_key: Some(
"78aaed50c54bc3912214991ad9b230ad3bc47c88e6504a81b65a4925372ba27f",
),
headernum: 8325312,
para_headernum: 1,
blocknum: 1,
state_root: "fd2e3e07ed2d610c6c0c6c3cd6858fff733fe53c03bd75d46f25e7c69dec490b",
dev_mode: false,
pending_messages: 0,
score: 0,
gatekeeper: Some(
GatekeeperStatus {
role: None,
master_public_key: "",
},
),
version: "0.2.4",
git_revision: "848b954d581c2fa60b1024cc7f3a1322b4ca027f", …
```
=> pherry: fix panics while using cache

crates/phactory/src/bin_api_service.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/system/gk.rs, crates/phactory/src/system/master_key.rs, crates/phactory/src/system/mod.rs, crates/phala-mq/src/types.rs, crates/phala-types/src/lib.rs, crates/phaxt/src/dynamic.rs, pallets/phala/src/registry.rs
This PR wraps contents signed by pRuntime with a content-type flag to make the system more secure.
None of the changes should break the already release software. May break the testnet though.
=> Wrap contents signed by pRuntime

scripts/run/build.sh
Hello, I followed the build instruction from https://github.com/Phala-Network/phala-blockchain/tree/master/scripts/run to build the project for the first time and failed, the error message said some git submodules are empty, this PR fixes the problem.
=> Fix: build script should update submodules first

Cargo.lock, crates/pink/pink-extension/Cargo.toml, crates/pink/pink-extension/src/logger.rs, crates/pink/src/contract.rs
This should fix the logging issues in the unit test.
Example changes: https://github.com/Phala-Network/fat-contract-examples/pull/3
=> pink-logger: Don't use log::* API

.github/workflows/build.yml, gramine.Dockerfile, rust-toolchain
In the future, it probably worth to add a `cargo contract create` test
=> Use Rust nightly-2022-09-08, newer can not compile ink contract for now

crates/pink/pink-extension-runtime/src/lib.rs, crates/pink/pink-extension-runtime/src/mock_ext.rs, crates/pink/pink-extension/src/chain_extension.rs, crates/pink/src/runtime/extension.rs
And rename the command to transaction.
Chan extension function availability:
| Function  | query | transaction |
| ------------- | ------------- |------------- |
| http_request  | ✅  | ❌ |
| sign(ecdsa/ed25519) |✅  |✅|
| sign(sr25519) | ✅  | ❌ |
| verify |✅  |✅|
| derive_sr25519_key |✅  |✅|
| get_public_key |✅  |✅|
| cache_set |✅  |✅|
| cache_set_expire |✅  |✅|
| cache_get |✅  |❌|
| cache_remove |✅  |✅|
| log |✅  |✅|
| getrandom |✅  |❌|
| is_running_in_command |✅  |✅|
| ecdsa_sign_prehashed |✅  |✅|
| ecdsa_verify_prehashed |✅  |✅|
=> pink: Disable sr25519 signing in tx

crates/phactory/src/bin_api_service.rs, crates/phala-rocket-middleware/src/lib.rs, crates/phala-rocket-middleware/src/response_signer.rs, pallets/phala/src/registry.rs, standalone/pherry/src/endpoint.rs, standalone/pruntime/src/api_server.rs, standalone/pruntime/src/runtime.rs
Example response:
```
< HTTP/1.1 200 OK
< content-type: text/plain; charset=utf-8
< server: Rocket
< permissions-policy: interest-cohort=()
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< x-phactory-signature: 08ce5ca7696d8ce9723aff1b2114de54489f86e1af153298a544a34c237dba50e7c1a8c766b6086c04ad7c7a5e5b4264547e42e4e48d6b2df9b9826e0388fe86
< content-length: 1274
< date: Fri, 23 Sep 2022 07:11:20 GMT
<
```
=> Sign public rpc response

Cargo.lock, crates/phaxt/src/rpc.rs, standalone/pherry/src/chain_client.rs, standalone/pherry/src/msg_sync.rs
It seems latest Subxt no longer expose the `client`
```
error[E0616]: field `client` of struct `subxt::rpc::Rpc` is private
--> crates/phaxt/src/rpc.rs:21:33
|
21 |             client: &self.rpc().client,
|                                 ^^^^^^ private field
Compiling pallet-child-bounties v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v0.9.29#7c4ac358)
error[E0308]: mismatched types
--> crates/phaxt/src/rpc.rs:21:21
|
21 |             client: &self.rpc().client,
|                     ^^^^^^^^^^^^^^^^^^ expected struct `Arc`, found struct `subxt::rpc::RpcClient`
|
= note: expected reference `&Arc<subxt::rpc::RpcClient>`
found reference `&subxt::rpc::RpcClient`
Some errors have detailed explanations: E0308, E0432, E0616.
For more information about an error, try `rustc …
```
=> Upgrade Subxt to v0.2.4

crates/phactory/src/prpc_service.rs
The root hash of Merkle Patricia Trie constructed by this KV vector needs to be checked against the state root in the header of the Genesis block.  `pherry` passes the KV vector of all the states of the Genesis block obtained by JSON-RPC `state_getPairs` to the `init_runtime` function of the `pRuntime` node.
Built success locally
Kusama Address： `EVYyMzs3Hg7NrVh3UQyvGKDmScc9XUV2yAQrY6DzTHVDCyL`   @kvinwang  @h4x3rotab  the address is it right? I am new to Polkadot/kusama eco. :)
=> Add verify state root for init_runtime

.github/actions/install_toolchain/action.yml, crates/phactory/src/storage.rs
We'd better release a teaclave-based pruntime with this patch before the chain launches #828.
=> [Backport] pruntime: Also pick messages from OutboundMessagesV2

Cargo.lock, crates/phactory/Cargo.toml, crates/phactory/api/src/endpoints.rs, crates/prpc-build/src/protos_codec_extension.rs, crates/sidevm/env/src/args_stack.rs, crates/sidevm/env/src/tests.rs, crates/sidevm/host-runtime/Cargo.toml, crates/sidevm/host-runtime/src/env.rs, crates/sidevm/host-runtime/src/env/wasi_env.rs, crates/sidevm/host-runtime/src/env/wasi_env/ptr.rs, crates/sidevm/host-runtime/src/run.rs, crates/sidevm/macro/src/macro_ocall.rs, crates/sidevm/macro/src/snapshots/sidevm_macro__tests__ocall.snap, crates/wasmer-tunables/Cargo.toml, crates/wasmer-tunables/src/lib.rs, standalone/pruntime/Cargo.lock
Wasmer 2.x will panic while compiling malformed WASM binaries. They fixed it on the 3.0 branch. Let's upgrade it.
=> sidevm: Use wasmer 3.0-beta

crates/phactory/src/prpc_service.rs
https://github.com/Phala-Network/phala-blockchain/pull/986 introduced the genesis state root check in init_runtime. However, this doesn't apply to parachain mode. Because the state_root in the genesis header is of the relaychain storage and the parachain header or state_root isn't available there.
=> pruntime: Skip genesis state root check in parachain mode

crates/phactory/api/src/storage_sync.rs, crates/prpc/src/lib.rs
As mentioned in [issue#992](https://github.com/Phala-Network/phala-blockchain/issues/992)
A display error terminate `cargo build --release` process.
```
error: expected identifier or literal
--> crates/phactory/api/src/storage_sync.rs:24:49
|
24 |     #[display(fmt = "HeaderValidateFailed({})", .0)]
|                                                 ^
error: could not compile `phactory-api` due to previous error
```
This error seems caused by display macro dependency had changed. The original code is compatible with [displaythis crate](https://docs.rs/displaythis/latest/displaythis/).
I replace 
```
pub enum Error {
/// Header validation failed
#[display(fmt = "HeaderValidateFailed({})", .0)]
HeaderValidateFailed(String),
/// Storage proof failed
#[display(fmt = "StorageProofFailed({})", …
```
=> fix display error in phactory-api

crates/phactory/src/prpc_service.rs, crates/phactory/src/system/gk.rs, crates/phaxt/src/dynamic/tx.rs, standalone/pherry/src/lib.rs
The latest Pherry can not be used to sync old pruntime since the AttestationProvider added.
This PR makes it compatible with old pRuntimes (with some other minor style refactor).
=> pherry: Talk to old pruntime

Cargo.lock, standalone/headers-cache/Cargo.toml, standalone/headers-cache/src/db.rs, standalone/headers-cache/src/grab.rs, standalone/headers-cache/src/main.rs, standalone/headers-cache/src/web_api.rs
This PR adds command line args to `headers-cache` to allow it auto grab new headers from chain nodes.
Usage:
```
ROCKET_PORT=8002 ./headers-cache serve --grab --node-uri=wss://miner-node.phala.network:443/kusama/ws --para-node-uri=wss://miner-node.phala.network:443/khala/ws
```
=> headers-cache: Auto grab new headers

crates/pink/pink-extension/src/lib.rs, crates/pink/pink-extension/src/logger.rs
This makes it easier to emit a log message in pink when some API returns a `Result::Err`.
It's similar to `Result::expect` but doesn't panic, and should be preferred over `expect`.
```rust
use pink::ResultExt;
let dollars = bank.withdraw(much).log_err("Failed to withdraw my money")?;
```
=> pink: Add helper Result::log_err

.github/actions/build-core/action.yml, .github/actions/build-prouter/action.yml, .github/actions/build-pruntime/action.yml, .github/workflows/build-nightly-release.yml, .github/workflows/build.yml
This PR adds GitHub action to build and publish nightly releases every morning.
- The artifacts would be published on the [GitHub Releases](https://github.com/Phala-Network/phala-blockchain/releases) page with the tag `Pre-release`.
- The binaries are built with `ubuntu-20.04`. So it might not run on other OS dist. Tried to build it with ubuntu-18.04 and the substrate failed to build. Also, GitHub Action will stop ubuntu-18.04 support on Apr 2023.
- We also do daily cleanup to old nightly releases, only the recent 30 releases are kept.
- Frontend tools can use [GitHub API](https://docs.github.com/en/rest/releases/releases#list-releases) to get a release list and download the assets from it. However, the API is almost unusable without authentication due to the [rate …
=> Add nightly build github action

crates/pink/src/runtime/extension.rs
When the contract calls an unavailable API in command, the contract call would panic.
Since the panic info is not visible in the logger, we make them return kinda default values rather than panic for a better debugging experience.
=> pink: Don't panic the guest if the chain extension is unavailable

Cargo.lock, standalone/headers-cache/Cargo.toml, standalone/headers-cache/src/grab.rs, standalone/headers-cache/src/main.rs, standalone/headers-cache/src/web_api.rs, standalone/pherry/src/headers_cache.rs
Two changes in this PR.
- Support setting `--justification-interval` for `serve --grab`.
The interval was set to `0` before. It is not a big deal if it is running on the guest side. However, if we deploy the `headers-cache` as a public service and want it to grab new headers while serving, it is important to be able to set the justification interval.
- Add an option `--mirror` to sync `headers-cache` from another headers-cache instance(the public one for example).
Mirroring
```bash
./headers-cache serve --mirror http://localhost:8003
```
@jasl
=> headers-cache: Add --mirror --justification-interval

crates/phactory/src/prpc_service.rs, crates/phactory/src/system/mod.rs, crates/pink/pink-extension-runtime/src/lib.rs, crates/pink/pink-extension-runtime/src/mock_ext.rs, crates/pink/pink-extension/src/chain_extension.rs, crates/pink/src/runtime.rs, crates/pink/src/runtime/extension.rs
This PR adds a chain extension `worker_pubkey` for pink query to get the worker's public key (identity). The feature is requested by @tolak.
Usage:
```rust
let worker_id = pink::ext().worker_pubkey();
```
Call it in a transaction would panic.
Note @h4x3rotab :
To simplify the implementation, we finally introduced another non-environmental global state in this PR.
Now we have two global states: the [`APPLICATION: Phactory`](https://github.com/Phala-Network/phala-blockchain/blob/c73e0c5fc3df7b082dd0960710d01fb77061bfbe/standalone/pruntime/src/runtime.rs#L9) created in pruntime bin and the WORKER_PUBKEY in crate `pink`.
=> pink: Add api worker_pubkey in Query

pallets/phala/src/registry.rs
Sample log
```
[Parachain] Decoded old 00021295869b1af27ab53a9070cb399483fbb4d43ef37bfd0da65c9d1b871755c39103f73845cf51: OldWorkerInfo { pubkey: , ecdh_pubkey: , runtime_version: 1, last_updated: 1633657680542, operator: Some(), confidence_level: 5, initial_score: Some(1416), features: [12, 2] }
[Parachain] Old: pubkey 7ab53a9070cb399483fbb4d43ef37bfd0da65c9d1b871755c39103f73845cf51 ecdh_pubkey 7ab53a9070cb399483fbb4d43ef37bfd0da65c9d1b871755c39103f73845cf51
[Parachain] Old: operator
[Parachain] worker key: 00021295869b1af27ab53a9070cb399483fbb4d43ef37bfd0da65c9d1b871755c39103f73845cf51
[Parachain] new 00021295869b1af27ab53a9070cb399483fbb4d43ef37bfd0da65c9d1b871755c39103f73845cf51: WorkerInfo { pubkey: , ecdh_pubkey: , runtime_version: 1, last_updated: 1633657680542, operator: Some(), …
```
=> Registry: Add migrate old workers extrinsic

Cargo.lock, crates/phactory/api/Cargo.toml, crates/prpc-build/Cargo.toml, crates/prpc-build/src/prost.rs, crates/prpc/Cargo.toml, standalone/pruntime/Cargo.lock
`prost-build` is no longer bundling with `protoc` from `0.11`. And the protoc installed with apt is too old to support `optional`. So, we use the `protoc` bundled in `prost-build 0.9` (which is 3.15.8) to build it.
=> Upgrade prost(-build) to 0.11

Cargo.lock, Cargo.toml, crates/phactory/Cargo.toml, crates/phactory/src/light_validation/justification.rs, standalone/pruntime/enclave/Cargo.lock, standalone/pruntime/enclave/Cargo.toml
The new finality-grandpa uses `parity-scale-codec-3` which is not compatible with the old pruntime codebase.
If we upgrade to use codec 3, it would be a huge change. So the simplest way is for finality-grandpa and downgrades its scale to 2.0.
=> [Back port] pruntime: Upgrade grandpa

crates/phactory/src/lib.rs
This fixes the checkpoint incompatible issue.
=> Don't store command args in checkpoint

crates/phactory/src/contracts/pink.rs, crates/phactory/src/system/mod.rs, crates/pink/src/contract.rs, crates/pink/src/runtime.rs, crates/pink/src/storage.rs
This distinguishes mutable/immutable execute fn in pink runtime to avoid unnecessary `&mut` requirements.
=> pink-runtime: Add immutable execute fn

Cargo.lock, crates/phactory/Cargo.toml, crates/phactory/api/src/blocks.rs, crates/phactory/src/lib.rs, crates/phactory/src/light_validation/mod.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/storage.rs, crates/phactory/src/system/gk.rs, crates/phactory/src/system/mod.rs, crates/phactory/src/types.rs, crates/phala-trie-storage/src/lib.rs, pallets/phala/src/puppets.rs, standalone/pruntime/Cargo.lock, standalone/replay/src/replay_gk.rs, standalone/replay/src/replay_gk/httpserver.rs
This PR gathers all codes, that get data from the chain storage with a manually composited key, into a single place.
So that we can easily audit it to see whether it is affected by the renaming PR. **Fortunately, nothing would be affected**.
Let's check it here: https://github.com/Phala-Network/phala-blockchain/blob/72b29828f5a3520309b79fa3dcc7f52324824443/crates/phactory/src/storage.rs#L82-L131
=> Refactor the chain storage inspecting in pRuntime

Cargo.toml, Makefile
**Summary**
This PR adds dylint support for this repository. The dylint rules are defined in a separate repository at https://github.com/Phala-Network/dylint-rules.
Currently, there is only one rule called `arithmetic_op` which warns against the usage of arithmetic operators.
**Why is it bad?**
Using arithmetic operators can cause arithmetic overflows, which can be a bad situation
in a blockchain infrastructure or smart contract.
`ink!` framework forces overflow checks to be enabled in build scripts, but the pruntime
does not.
Regardless of whether the framework enables checks, we should always be careful when doing
arithmetic calculations.
**Example:**
Instead of:
```rust
// example code where a warning is issued
let released = original_stake - slashed;
```
Prefer:
```rust
// example …
```
=> Add dylint with custom lint rules

crates/phactory/api/src/storage_sync.rs, crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/storage.rs, crates/phala-types/src/lib.rs, pallets/phala/src/fat_tokenomic/tests/mock.rs, pallets/phala/src/mock.rs, pallets/phala/src/registry.rs, standalone/runtime/src/lib.rs
Otherwise, it can register workers synced state from other parachain on phala's parachain.
Key points:
- Remember the `para_id` from the `genesis state` passed in by `init_runtime`.
- Seal the para_id into the `runtime-data.seal` and ensure it matches in later `init_runtime`. This make sure the identity key would not be used to sync data from other parachain.
- Use the para_id from the `genesis state` rather than get it from each block state to validate the para header.
- Ensure the para_id reported by pRuntime matches the para_id of the chain in `fn register_worker_v2`.
=> Check parachain id in worker registering

crates/phactory/api/src/storage_sync.rs, crates/phactory/pal/src/lib.rs, crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/storage.rs, crates/phactory/src/system/master_key.rs, crates/phactory/src/system/mod.rs, crates/phala-trie-storage/src/lib.rs, crates/phala-types/src/lib.rs, crates/phaxt/src/chain_api.rs, crates/prpc-build/src/protos_codec_extension.rs, e2e/src/fullstack.js, e2e/src/proto/pruntime_rpc.d.ts, e2e/src/proto/pruntime_rpc.js, pallets/phala/src/fat_tokenomic/tests/mock.rs, pallets/phala/src/mock.rs, pallets/phala/src/registry.rs, standalone/justification-validate/src/validator.rs, standalone/pherry/src/chain_client.rs, standalone/pherry/src/lib.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/Cargo.toml, standalone/pruntime/src/api_server.rs, standalone/pruntime/src/main.rs, standalone/pruntime/src/pal_gramine.rs, standalone/runtime/src/lib.rs
3 major changes in this PR:
- pRuntime: Added a new prpc::LoadChainState
which can load a given block of chain state into pRuntime if the worker hasn't been registered at that block.
- pherry: Added a new option `--fast-sync`
which finds a suitable chain state for pRuntime and loads it.
- Changed the previous mq message PRuntimeManagement to using chain storage as flags for version management.
Because pRuntime can load from arbitrary block state, it can not rely on mq to maintain the states in pRuntime now.
Another change in this PR:
- By default, without `load_chain_state`, pruntime will require syncing para headers starting from `0`(`para_headernum = 0` in get_info, it was `1` before) to validate the genesis state. CC @krhougs 
Since the GK requires tracking all workers' states, …
=> Support fast sync new workers

Cargo.lock, crates/phaxt/Cargo.toml, crates/phaxt/src/lib.rs
This should fix the `Error: Connection(MessageTooLarge { current: 15336981, maximum: 10485760 })`.
=> pherry: Unlimited ws body size

pallets/phala/src/utils/balance_convert.rs
A simpler version of #1093 
After the conversion, U64F64 itself can store `1.8*10^19` PHA. It should be enough for other calculations.
@h4x3rotab How do you think about this approach?
=> Fix overflow in FixedPointConvert

pallets/phala/src/compute/base_pool.rs, pallets/phala/src/compute/stake_pool_v2.rs
**Add legacy rewards features**
Introducing new storage and two functions In order to fix the calculation mistake when migrating legacy stake rewards.
1.push_legacy_rewards_data
Push legacy rewards data calculated off-chain into the on-chain storage so that user could claim their rewards further.
2.claim_legacy_rewards
Allow user to claim their legacy rewards into the assigned account.
**Remove locks features**
Fix on-chain storage boost problem by remove locks in function burn_nft and providing historical data remove functions
1.remove_unused_lock
iterate the `Lock` storage map and remove items that not belongs to any nft alive, has a max iteration limitation.
=> Add legacy rewards features and remove locks features

pallets/phala/src/compute/base_pool.rs, pallets/phala/src/mock.rs, standalone/runtime/src/lib.rs
**background**
The panic occurred when the withdrawal amount was less than the transfer function's min balance.
**fix**
Introducing min_balance const by runtime config, and only when the transfer amount is larger than the min balance, the transfer would actually happen; if not, we will just regard it as dust and erase it. And the free balances of the pool will also be checked in the same way when iterating withdrawal procession instead of the former check dust.
=> FIX process_withdraw_queue panic issue

Cargo.lock, crates/phactory/Cargo.toml, standalone/pruntime/Cargo.lock
It's a trivial update though. Only logs or code style changed from `0.16.0` to `0.16.1`: https://github.com/paritytech/finality-grandpa/compare/eb26b0c86dbb6949435b627f85eceb026f96ebe9..218cdc68568cf30c536070a92336686f3df67a9c
=> Bump grandpa to 0.16.1

crates/phactory/api/Cargo.toml, crates/prpc/Cargo.toml, crates/prpc/src/lib.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/Cargo.toml, standalone/pruntime/src/handover.rs, standalone/pruntime/src/main.rs
This PR adds a new argument `--request-handover-from` to pruntime. Which allows doing handover without a third program.
Another benefit is the new pruntime doesn't require listening on any TCP port while doing handover.
Usage:
```bash
./pruntime --request-handover-from http://localhost:8000
```
Codes are copied from:
https://github.com/Phala-Network/phala-blockchain/blob/29f046e0d49bba0af405c2c617be414a9a339711/standalone/pherry/src/lib.rs#L1526-L1532
=> pruntime: Builtin handover coordinator

crates/pink-libs/subrpc/src/hasher.rs, crates/pink-libs/subrpc/src/lib.rs, crates/pink-libs/subrpc/src/storage.rs
The following interfaces have changed:
`pub fn storage_map_blake2_128_prefix(prefix: &[u8], key1: &[u8]) -> Vec<u8>` and `storage_double_map_blake2_128_prefix(prefix: &[u8], key1: &[u8], key2: &[u8])` are all deprecated, they have been replaced by a group of generic functions: `pub fn storage_map_prefix<H: Hasher>(prefix: &[u8], key1: &[u8]) -> Vec<u8>` and `pub fn storage_double_map_prefix<H1: Hasher, H2: Hasher>(
prefix: &[u8],
key1: &[u8],
key2: &[u8],
) -> Vec<u8>`.
In this way, we can specify any supported hash functions we want to compute the storage key
=> [subrpc] Make storage key computing more generic

standalone/headers-cache/src/grab.rs, standalone/headers-cache/src/main.rs
This allows to start `headers-cache serve --grab` without the pre-requirement of `grab and import` steps.
For example:
```
./target/release/headers-cache serve --grab --node-uri wss://miner-node.phala.network:443/kusama/ws --para-node-uri wss://miner-node.phala.network:443/khala/ws
```
=> Starting serve and --grab without pre-imported headers

standalone/headers-cache/src/grab.rs, standalone/headers-cache/src/web_api.rs
=> Some optimizations to headers-cache

crates/phactory/src/prpc_service.rs
This is useful for pruntime troubleshooting.
=> Add log for get_info

Cargo.lock, crates/pink-libs/kv-session/Cargo.toml, crates/pink-libs/kv-session/src/rollup.rs, crates/pink-libs/kv-session/src/session.rs, pallets/offchain-rollup/src/anchor.rs
Bump kv-session to v0.2.0 as API is changed.
When working with pink-web3 (EVM), I've created a contract object in the KvSnapshot impl. When committing, the object will be passed to `rollup()`, and its lifecycle ends. Since the contract object is heavy, it's ideal to reuse the object to submit transactions after calling `rollup()`. So in this PR, I propose to make the argument a reference for easier object reuse.
=> kv-session: loosen rollup() KvSnapshot to ref

crates/phactory/src/system/gk.rs, crates/phala-mq/src/dispatcher.rs, crates/phala-types/src/lib.rs, pallets/phala/src/registry.rs
It was added in #768. The WorkerInfo is an mq message sent from the chain to pRuntime. If we change the codec layout, pRuntime would fail to decode the history message and abort.
We can add a `WorkerEvent::RegisteredV2` if we want to add more information to the structure in the future.
=> Remove attestation_provider from the WorkerEvent::Registered

Cargo.lock, crates/phactory/api/Cargo.toml, standalone/headers-cache/Cargo.toml, standalone/pherry/Cargo.toml, standalone/prouter/Cargo.lock, standalone/pruntime/Cargo.lock
This PR removes the dependency on OpenSSL for pruntime, pherry, headers-cache, etc.
This should fix #1142.
=> Remove dependency on OpenSSL

Cargo.lock, crates/phactory/src/contracts/pink.rs, crates/phala-trie-storage/Cargo.toml, crates/phala-trie-storage/src/lib.rs, crates/phala-trie-storage/src/memdb.rs, crates/phala-trie-storage/src/ser.rs, crates/pink/src/contract.rs, crates/pink/src/storage.rs, standalone/pruntime/app/Cargo.lock, standalone/pruntime/enclave/Cargo.lock
For the pruntime v0, we use the MemoryDB from Substrate as the backend of the TrieDB.
Because the MemoryDB neither implements serde traits nor supplies a cheap API to get the inner KV store. So we did have to clone the entire TrieDB to take checkpoints. **That causes peak memory usage to be twice the KV store**.
In purntime-v2, we implemented a custom MemoryDB based on `im::HashMap` to support cheap snapshots for queries. As a side effect, it also makes taking checkpoints cheaper(Doesn't need to clone the entire TrieDB).
This PR backports the implementation so that taking checkpoints won't require much more memory. However, there is also an overhead: the memory cost of `im::HashMap` is larger (not much) than `std::_::HashMap`.
For example, here is a sample from about 2 months ago:
``` …
```
=> Backport custom MemoryDB to pruntime v0

Cargo.lock, Cargo.toml, crates/phactory/Cargo.toml, crates/phactory/src/contracts/pink.rs, crates/phala-trie-storage/Cargo.toml, crates/phala-trie-storage/src/lib.rs, crates/phala-trie-storage/src/memdb.rs, crates/phala-trie-storage/src/ser.rs, crates/pink/src/contract.rs, crates/pink/src/storage.rs, crates/sp-trie/Cargo.toml, crates/sp-trie/README.md, crates/sp-trie/src/error.rs, crates/sp-trie/src/lib.rs, crates/sp-trie/src/node_codec.rs, crates/sp-trie/src/node_header.rs, crates/sp-trie/src/storage_proof.rs, crates/sp-trie/src/trie_codec.rs, crates/sp-trie/src/trie_stream.rs, standalone/pruntime/app/Cargo.lock, standalone/pruntime/enclave/Cargo.lock
I've tried to upgrade the entire substrate in #1118, but encountered a bunch of troubles difficult to resolve.
Instead, this PR backports the sp-trie that supports TrieLayoutV1 to pruntime-v0.
There are tens of commits modifying `sp-trie` in the substrate from the version pruntime-v0 uses to polkadot-v0.9.36:
```
* fafc8e0ba8 - Remove `mem_info` and references to `parity-util-mem` (#12795) (6 weeks ago) <Marcin S>
* 108d8eed88 - (tag: sp-runtime-v7.0.0, tag: sp-core-v7.0.0) release `sp-core 7.0.0` and `sp-runtime 7.0.0` (#12599) (9 weeks ago) <Niklas Adolfsson>
* c460f4be08 - Update some dependencies to prune duplicated crates with different version (#12560) (10 weeks ago) <Qinxuan Chen>
* a1dee7ecd2 - Remove partial key size limit from trie codec (#12566) (10 weeks ago) <cheme>
* …
```
=> Backport TrieLayoutV1 to pruntime-v0

pallets/phala/src/compute/base_pool.rs, pallets/phala/src/compute/stake_pool_v2.rs, pallets/phala/src/compute/vault.rs, pallets/phala/src/compute/wrapped_balances.rs, pallets/phala/src/test.rs
**Background**
Current stake pool v2 introduced a lot of mint_nft and burn_nft when merging a user's nfts in a collection, many of them are unnecessary and it leads to storage being overwhelmed on the runtime. 
And some of the unused codes are removed in this pr by the way.
**Solutions**
1. Changing the function merge_nfts_for_stakers by reducing burn and mint in unnecessary cases
2. The frontend will show nfts basic information generated on their own instead of using nft-properties in on-chain storages So that we can no longer write these data on-chain.
=> Optimization of storage usage in Stakepool v2

standalone/pherry/src/lib.rs
I found some people are confused by the arg name `--substrate-ws-endpoint` and  `--collator-ws-endpoint`.
This PR renamed it to a clearer name and aliases the origin names to the new ones.
=> pherry: Rename node endpoint arguments

Cargo.lock, crates/phactory/api/src/ecall_args.rs, crates/phactory/api/src/pruntime_client.rs, crates/phactory/api/src/storage_sync.rs, crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/system/mod.rs, crates/phala-trie-storage/Cargo.toml, crates/phala-trie-storage/src/lib.rs, standalone/pherry/src/lib.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/src/api_server.rs, standalone/pruntime/src/main.rs, standalone/pruntime/src/runtime.rs
This PR adds `--safe-mode-level` to prevent bricking the whole system by some unexpected fault in pruntime.
- 0, All features enabled.
- 1, Sync blocks without dispatching messages. Sidevm and contract query are disabled.
- 2,  In addition to level 1, this level neither stores the trie proofs to reduce memory usage.
In this mode, it is needed to invoke `prpc.LoadStorageProof` to load the necessary values
before accepting key handover requests.
=> pruntime: Add safe mode

crates/phactory/src/prpc_service.rs, crates/phactory/src/system/mod.rs, standalone/pherry/src/lib.rs
This is a fixup to the PR [Safe mode](https://github.com/Phala-Network/phala-blockchain/pull/1157)
Because the info in System would never be updated in safe mode.
=> handover: Read timestamp from chain storage instead of System

Cargo.lock, pallets/phala/src/compute/wrapped_balances.rs, standalone/prouter/Cargo.lock, standalone/pruntime/Cargo.lock
Temporarily forbid delegation Nft transformation by simply returning `false` in the transfer pre_check hook.
=> Forbid nft transfer in pre_check function

Cargo.lock, crates/phala-node-rpc-ext/Cargo.toml, crates/phala-node-rpc-ext/src/storage_changes.rs
We have got a deadlock in the `khala-node` while getting storage changes.
According to the gdb stack frame dump, we found the deadlock is caused by the following flow:
```
[time 0] Thread A: locked(rayon default thread pool) in `pha_getStorageChanges`.
[time 1] Thread B: locked(sp wasm runtime cache) in block executor.
[time 2] Thread B: acquiring (rayon default thread pool) in `fn runtime_version`.
[time 3] Thread A: acquiring (sp wasm runtime cache) `fn runtime_version`.
```
Ideally, this can be solved by replacing the rayon thread pool used in `pha_getStorageChanges` with a separate pool rather than the default one.
However, due to the thread pool API of rayon:
```rust
thread_pool.install(|| {
let result = headers
.into_par_iter()
.for_each(|| { /*do the work*/ })
.collect();
})
``` …
=> node-rpc-ext: Remove rayon (Fix deadlock)

standalone/headers-cache/src/main.rs, standalone/pherry/src/headers_cache.rs
=> headers-cache: Finish grabing storage gracefully

crates/phactory/api/src/ecall_args.rs, standalone/pruntime/src/main.rs
Remove it because there is no longer a GC in the HashDB.
=> pruntime: Remove --gc-interval

pallets/phala/src/compute/base_pool.rs
Fixed a bug that will lead to dead loop when user call `withdraw` while the `PoolAccount`'s balance reach the min limit.
=> Fix dead loop

Cargo.lock, crates/phactory/api/Cargo.toml, crates/phactory/api/build.rs, crates/phactory/api/src/proto_generated/mod.rs, crates/phactory/src/prpc_service.rs, crates/prpc-build/src/server.rs, crates/prpc/Cargo.toml, crates/prpc/src/lib.rs, docs/rpc.md, standalone/pruntime/Cargo.lock, standalone/pruntime/src/api_server.rs, standalone/pruntime/src/runtime.rs
The PR adds support for talking to the pRPC with JSON input/output. This makes it easier for more external tools to connect to pruntime RPC.
Example:
Via GET:
```bash
$ curl localhost:8000/prpc/PhactoryAPI.GetInfo
```
Via POST with a query argument `json`:
```bash
$ curl -d "" localhost:8000/prpc/PhactoryAPI.GetInfo?json
```
Or via POST with the Content-Type of JSON:
```bash
$ curl -d "" -H "Content-Type: application/json" localhost:8000/prpc/PhactoryAPI.GetInfo
```
With any of the above calls, the RPC will respond in JSON format:
```json
{"initialized":false,"registered":false,"genesis_block_hash":null,"public_key":null,"ecdh_public_key":null,"headernum":0,"para_headernum":0,"blocknum":0,"state_root":"","dev_mode":false,"pending_messages":0,"score":0,"gatekeeper":{"role":0,"master_public_ …
```
=> pRPC: Support JSON

standalone/pruntime/Cargo.lock, standalone/pruntime/Cargo.toml, standalone/pruntime/src/main.rs, standalone/pruntime/src/pal_gramine.rs
Requested by @jasl 
Info printed on startup:
```
$ ./gramine-sgx pruntime --version
Gramine is starting. Parsing TOML manifest file, this may take some time...
...
Running in Gramine-SGX
mr_enclave  : 0xb944d736f53e398e2f0167a8f84290b98a87d418318ed75efd9661f71ab66d0d
mr_signer   : 0x83d719e77deaca1470f6baf62a4d774303c899db69020f9c70ee1dfc08c7ce9e
isv_svn     : 0x0000
isv_prod_id : 0x0000
pruntime 2.0.1
```
=> pruntime: Print enclave info on startup

Cargo.lock, crates/pink/pink-extension/Cargo.toml, crates/pink/pink-extension/src/allocator_dlmalloc.rs, crates/pink/pink-extension/src/lib.rs
The default Rust allocator in ink doesn't free any memory at all. It would be a problem in some situations such as in the js engine contract.
This PR solves it by adding a feature `dlmalloc` to the pink crate. This makes it convenient to switch the Rust allocator to the dlmalloc allocator.
Usage:
In Cargo.toml:
```
pink-extension = { version = "0.4", default-features = false, features = ["dlmalloc"] }
```
cc @tolak @tenheadedlion
=> pink: Add optional allocator: dlmalloc

crates/phala-trie-storage/src/lib.rs, crates/phala-trie-storage/src/memdb.rs, crates/phala-trie-storage/src/ser.rs
The `im::HashMap` has a really heavy memory overhead. Let's use `im::OrdMap` to reduce memory usage.
`im::OrdMap` is a bit slower than `im::HashMap`. It took about `57 minutes` to sync from block height 0 to 900000 vs `52 minutes` for `im::HashMap`.
=> TrieDB: use im::OrdMap to reduce memory consumption

Cargo.lock, standalone/headers-cache/Cargo.toml, standalone/headers-cache/src/main.rs, standalone/headers-cache/src/web_api.rs, standalone/headers-cache/src/web_api/auth.rs, standalone/pherry/Cargo.toml, standalone/pherry/src/headers_cache.rs
Sometimes, headers-cache would grab broken block data from the chain node.
This PR adds 3 web APIs for headers-cache to upload in order to hot fix those broken data without interrupting the service.
Usage:
Startup headers-cache with a token:
```bash
ROCKET_PORT=8002 ./headers-cache serve --grab-headers --grab-para-headers --grab-storage-changes --token 123
```
Assuming that block 3532919 is broken, we can fetch the block from another node:
```bash
./headers-cache grab storage-changes --para-node-uri ws://the-node:9944 --from-block 3532919 --count 1 storage-changes.bin
```
Then patch the broken block by upload the file:
```bash
curl -XPUT -H "X-Token: 123" --data-binary @storage-changes.bin localhost:8002/storage-changes
```
@jasl
=> headers-cache: Support for hot fixing blocks

pallets/phala/src/compute/wrapped_balances.rs
Fixed a potential problem that may trigger the `StakerAccountNotFound` error event when a vault owner claim his owner shares into balances and try to re-delegate.
=> Fix vault owner shares redelegate problem

crates/phactory/src/lib.rs, crates/phala-git-revision/build.rs, crates/phala-git-revision/src/lib.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/Cargo.toml, standalone/pruntime/src/main.rs
This PR append the `git commit timestamp` to the `git_revision` in `get_info`:
```bash
$ curl -s localhost:8000/prpc/PhactoryAPI.GetInfo | jq .git_revision
"7cab7494121109a227b2460d0703fb97fdc3f4fd-20230321070215"
```
This makes some troubleshooting easier.
=> pruntime: Show timestamp in git revision

.github/workflows/build.yml, Cargo.lock, Cargo.toml, crates/phala-wasm-checker/Cargo.toml, crates/phala-wasm-checker/src/error.rs, crates/phala-wasm-checker/src/lib.rs, crates/pink/runtime/Cargo.toml, crates/pink/runtime/src/capi/ecall_impl.rs, crates/pink/runtime/src/runtime.rs
This pull request introduces a pre-check mechanism for uploading ink code to cluster storage. The check verifies that the code does not exceed 4 times the MaxCodeLen limit when parsed into wasmi's memory representation.
=> pink-runtime: Limit parsed ink code size

standalone/pruntime/gramine-build/pruntime.manifest.template
This fixes the stack overflow issue while loading checkpoints.
=> pruntime: Increase stack size to 1MB

pallets/phala/src/compute/computation.rs
Double the maxbudgetlimit to compensate budget miss-caculated during the last nonce.
=> double budget limit

crates/phactory/src/contracts/pink.rs, crates/phactory/src/contracts/support.rs, crates/phactory/src/system/mod.rs, crates/pink-drivers/log_server/sideprog/src/buffer.rs, crates/sidevm/env/src/messages.rs
This PR Adds a field `entry`(stands for the entry contract id) to log items being sent to the log server, a feature requested from @shelvenzhou,  as shown below:
This should be the last feature added to milestone 2.0.
**Breaking**
This would break the communication between pruntime and the contract log_server. That's saying, the new log_server can not work with the previous versions of pruntime or vice versa.
No external APIs changed.
=> pruntime: Add entry contract to pink log records

standalone/pruntime/src/api_server.rs
I found the `tracing::instrument` on pRPCs no longer works after we upgraded the Rocket to 0.5-rc3:
```
[2023-03-23T10:57:30.586276Z INFO  phactory::prpc_service] Dispatching request: PhactoryAPI.DispatchBlocks
[2023-03-23T10:57:30.586314Z INFO  phactory::prpc_service] dispatch_block from=Some(1) to=Some(4)
[2023-03-23T10:57:30.586320Z INFO  phactory::prpc_service] Dispatching block: 1
```
Swapping the attribute macro order fixes the issue:
```
2023-04-11T08:19:17.156303Z  INFO prpc{id=42}: phactory::prpc_service: Dispatching request: PhactoryAPI.DispatchBlocks
2023-04-11T08:19:17.157606Z  INFO prpc{id=42}: phactory::prpc_service: dispatch_block range=(Some(3291234), Some(3291237))
2023-04-11T08:19:17.157629Z  INFO prpc{id=42}: phactory::prpc_service: Dispatching block=3291234
```
=> pruntime: Fix tracing instrument on pRPC

pallets/phala/src/compute/vault.rs, pallets/phala/src/compute/wrapped_balances.rs
1.Fixed a problem that when a vault owners gain his owner shares, the vault will not be added into his `subscribe_pools`.It may lead to his net_value miscalculation.
2.`wrap` now will create a new account_status data every time it is called which is clearly an bug, the push fix it and added a remedy function to update account_status.locked to correct value.
=> add may be subscribe pools & fix `wrap` clean account_status issue

crates/pink/runner/src/storage.rs
The trie framework will pass an empty value when the `rc` is negative. So, the value would be mis-cleared when decreasing the rc.
This PR fixes it by setting the value only when `rc > 0`.
=> pruntime: Fix trie node corruption

Cargo.lock, crates/pink/pink-extension/Cargo.toml, crates/pink/pink-extension/macro/Cargo.toml, crates/pink/pink-extension/macro/src/chain_extension.rs, crates/pink/pink-extension/macro/src/contract.rs, crates/pink/pink-extension/macro/src/driver_system.rs
ink_codegen-4.2 has updated syn from `1.0` to `2.0` which broke our downstream phat contracts compilation.
Let's update it too.
=> pink-macro: Update syn from 1.0 to 2.0

pallets/phala/src/compute/computation.rs, pallets/phala/src/mock.rs, pallets/phala/src/registry.rs, pallets/phala/src/test.rs, standalone/runtime/src/msg_routing.rs
Gatekeepers track the state of workers starting from their initial registration event. If any worker registered before the first Gatekeeper was launched begins computing without re-registering, the Gatekeeper will not be able to track their entire state, leading to inconsistent worker states and further panic.
This pull request ensures that all workers registered prior to the launch of the first Gatekeeper must re-register in order to be added to a pool.
=> Prevent early registered workers from being added to pools

pallets/phala/src/registry.rs
This PR
- Fixes the unit of last_updated.
- Hard forbid workers added before GK launching no matter whether it is registered later.
=> Fix last_updated & Hard forbid workers added before GK launch

pallets/phala/src/compute/base_pool.rs, pallets/phala/src/test.rs
**Background**
When a pool tries to process its withdraw queue, it will make sure the withdraw is partially fulfilled, if not, we will drop the dust withdraw Nft. But in extreme condition, if the withdraw is already a dust on the first loop, we will throw a panic that the balance amount is too low before we drop the dust at the end of every loop.
**Solution** 
We will check if the withdraw is a dust in the first place the loop begins.
=> fix dust panic on first loop

crates/pink-drivers/log_server/sideprog/Cargo.toml
Before strip:
2.17 MB
After strip:
244K
=> Strip log_server.sidevm.wasm

pallets/phala/src/compute/base_pool.rs, pallets/phala/src/compute/stake_pool_v2.rs, pallets/phala/src/compute/vault.rs, pallets/phala/src/mock.rs, standalone/runtime/src/lib.rs
Fix two edge cases that will let vault's withdraw_queue proceed itself unexpected.
1.Currently the vault could contribute to stakepools even if it is locked.It will lead to a edge case that the vault's stakepool-withdrawal will be re-contribute to stakepools before it satisfy the vault's withdraw_queue which it should do. It will lead to the vault locked forever and users can not reclaim his withdrawal.
We now forbid the vault to contribute to stakepools when it is locked, and we add a additional call that could unlock the vault then re-check it for those vaults already met this edge case.
2.Forbid a potential case that vault owner can keep users' delegation in the pool longer than the grace_period by adding a vault_queue_period which has 21 days limitation before it is forced to …
=> fix vault withdraw_queue edge issue

Cargo.lock, crates/phactory/Cargo.toml, crates/phactory/src/prpc_service.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/gramine-build/pruntime.manifest.template
This PR might fix #1188.
This PR increases the default max brk size in Gramine from 128KB to 256MB to address an issue in Glibc where, upon falling back to mmap for memory allocation when heap memory exceeds the threshold, the allocated memory is never returned to the system even after being released by the app. As a consequence, Gramine LibOS will preallocate memory for it of the max_size, which is acceptable. 
An alternative solution to consider is using different allocators.
=> pruntime: Increase brk max size to 256M

pallets/phala/src/compute/computation.rs, pallets/phala/src/mock.rs, standalone/runtime/src/lib.rs
The worker-checking logic was introduced for Phala and later new test networks. It was launched to Khala by mistake and caused the following error:
This PR adds an option to turn it off. And please set it to false on Khala. @jasl
=> pallet_compute: Add option to disable worker reg time checking

pallets/phala/src/compute/base_pool.rs, pallets/phala/src/compute/stake_pool_v2.rs, pallets/phala/src/compute/wrapped_balances.rs, pallets/phala/src/mock.rs, pallets/phala/src/test.rs, standalone/runtime/src/lib.rs
When the calculated reward (to either the pool owner, or the pool distribution reward) is below ED, and the corresponding accounts are new, pallet-assets will refuse to mint the WPHA. In such case, we should handle it carefully as below:
- If the pool is already frozen (pool's total share < share dust), dismiss the reward entirely;
- If the reward is below the dust, dismiss the reward entirely;
- Otherwise, the reward will be divided into `owner` and `to_distribute` rewards, and will be distributed separately:
- The total reward will be transferred to `wrapped_balances` to increase its reserve.
- Mint WPHA to the owner reward account for owner commission. However if it's below WPHA ED, it will be dismissed;
- Mint WPHA to the pool income account for staker reward. However if it's below …
=> Fix reward below min balance (ED)

Cargo.lock, crates/phactory/src/contracts/pink.rs, crates/pink/capi/src/v1/mod.rs, crates/pink/pink-extension-runtime/Cargo.toml, crates/pink/pink-extension-runtime/src/lib.rs, crates/pink/pink-extension-runtime/src/mock_ext.rs, crates/pink/pink-extension/Cargo.toml, crates/pink/pink-extension/src/chain_extension.rs, crates/pink/pink-extension/src/chain_extension/http_request.rs, crates/pink/runner/tests/test_pink_contract.rs, crates/pink/runtime/src/runtime/extension.rs, e2e/contracts/check_system/lib.rs, e2e/src/fullstack.js, e2e/src/utils/pm.js, standalone/pruntime/Cargo.lock
This PR adds a new extension function to send multiple HTTP requests simultaneously:
```rust
#[ink(extension = 22, handle_status = true)]
fn http_batch_request(
requests: Vec<HttpRequest>,
timeout_ms: u64,
) -> Vec<Result<HttpResponse, HttpRequestError>>;
```
The PR requires runtime upgrading for the already deployed cluster.
Usage:
https://github.com/Phala-Network/phala-blockchain/pull/1280/files#diff-ede8afeb0bf8928e02cd43f590808488c91465e013f2be7cc8adbf9b1715dad2R119-R140
=> pink: Support for batch HTTP request

.github/actions/install_toolchain/action.yml, gramine.Dockerfile, rust-toolchain.toml
Our phat contracts don't compile with rustc 1.70
See the follow links for more detail:
https://github.com/paritytech/cargo-contract/issues/1139
https://github.com/rust-lang/rust/issues/109807
=> Pin Rustc to 1.69

.dockerignore, Cargo.lock, Cargo.toml, crates/phactory/api/src/pruntime_client.rs, crates/phaxt/src/chain_api.rs, crates/pink-libs/utils/src/attestation.rs, crates/pink-libs/utils/src/lib.rs, dockerfile.d/01_apt.sh, dockerfile.d/05_rust.sh, gramine.Dockerfile, poller.Dockerfile, standalone/phat-poller/Cargo.toml, standalone/phat-poller/src/app.rs, standalone/phat-poller/src/args.rs, standalone/phat-poller/src/contracts.rs, standalone/phat-poller/src/instant.rs, standalone/phat-poller/src/main.rs, standalone/phat-poller/src/query.rs, standalone/phat-poller/src/web_api.rs
For @shelvenzhou 
```
Usage: phat-poller run [OPTIONS] --factory-contract <FACTORY_CONTRACT>
Options:
--node-uri <NODE_URI>
The URI of a phala-node [default: ws://localhost:9944]
--dev-worker-uri <DEV_WORKER_URI>
The worker URL used to development
--cluster-id <CLUSTER_ID>
Cluster ID [default: 0x0000000000000000000000000000000000000000000000000000000000000001]
--max-history <MAX_HISTORY>
Max number of history tasks to keep in [default: 200]
--probe-interval <PROBE_INTERVAL>
The interval to update and probe the worker list [default: 5m]
--probe-timeout <PROBE_TIMEOUT>
The timeout to probe a worker [default: 5s]
--poll-interval <POLL_INTERVAL>
Contract poll interval [default: 10s]
--poll-timeout <POLL_TIMEOUT>
Contract poll timeout [default: 10s]
--use-top-workers <USE_TOP_WORKERS>
Top n …
```
=> Add Phat Bricks Poller

standalone/phat-poller/src/query.rs
It doesn't matter for the phat-poller, but let's fix it to avoid confusing people.
=> phat-poller: Randomize the iv

Cargo.lock, crates/sidevm/host-runtime/Cargo.toml, crates/sidevm/host-runtime/src/env.rs, crates/sidevm/host-runtime/src/env/wasi_env.rs, crates/sidevm/host-runtime/src/env/wasi_env/ptr.rs, crates/sidevm/host-runtime/src/run.rs, standalone/pruntime/Cargo.lock
The PR upgrades Wamser to 3.3. Which will ideally solve the crash on J4125.
Note:
This PR also introduces [a new piece of unsafe code](https://github.com/Phala-Network/phala-blockchain/pull/1301/files#diff-155e40761236bcfaefd6481c042598ba0b9f32e3091f7cb2a38124751f46aca9R698) that transmutes the memory reference lifetime:
=> Upgrade wamser to 3.3

crates/pink-drivers/system/lib.rs, crates/pink-drivers/tokenomic/lib.rs, crates/pink/pink-extension/src/system.rs
Split from [pink: Add API code_history](https://github.com/Phala-Network/phala-blockchain/pull/1287).
We might still want this feature since it's low overhead and make it more convenient to audit the drivers.
=> pink: Add API driver_history

crates/pink-drivers/log_server/sideprog/Cargo.toml, crates/pink-drivers/log_server/sideprog/src/buffer.rs, crates/pink-drivers/log_server/sideprog/src/lib.rs
As @shelvenzhou reported, the sidevm of the contract `log_server` panics due to OOM. 
See #1325 for the misleading of the error message.
I've checked it with random test logs and didn't see memory leak in the sidevm program.
The size of logs was limited with a soft bound of 8MB. However, we **under-estimated** the current log size with a rough formula.
Counting in the overhead, the actual memory cost was **far more than 8MB**. And a large tmp memory blob is required when a query requests all log records. This could make the guest run out of memory.
This PR makes 2 improvements:
- Using the metric reported from the memory allocator as the records size bounds. This should be more accurate than the estimated one before.
- Boxing each single log record. This could reduce the overhead of the …
=> Fix the OOM in log_server

crates/sidevm/host-runtime/src/env.rs, crates/sidevm/host-runtime/src/env/wasi_env.rs, crates/sidevm/host/Cargo.toml, crates/sidevm/host/src/main.rs, crates/sidevm/host/src/web_api.rs
@shelvenzhou recently found that the log_server sometimes panicked with the following error:
The error message is misleading. The error itself was raised from the fn `std::io::Write::write_all`, but there isn't any code in our source call that fn. I've checked the wasm code with `wasm2wat`.
After some investigating, I finally found the error is raised inside the oom_handler [here](https://github.com/rust-lang/rust/blob/7f01f030613fb6ffe06d5f5791a273d384cd6f55/library/std/src/alloc.rs#L343) in the libstd. The oom_handler tries the write some message to stderr rather than panic when targeting wasm, but failed to write to the fd because our runtime doesn't support for writing data to any fd.
This PR allow the guest to write to stdout and stderr, only for showing this kind of errors. It would …
=> sidevm: Allow writing to stdout and stderr

crates/phala-sanitized-logger/src/subscriber.rs
pRuntime use `SanitizedSubscriber` to filter out logs from other crates. `SanitizedSubscriber` is implemented as a thin wrapper over `tracing_subscriber::fmt::Subscriber`. 
However, in the implementation, the methods which have default implementations in the `trait Subscriber` haven't been forwarded to `fmt::Subscriber`. This cause the resource management in `fmt::Subscriber` broken.
This PR fixes it by forwarding all methods to the inner subscriber.
=> pruntime: Fix memory leak in logging

crates/phala-sanitized-logger/src/subscriber.rs
backport #1318 to `libpink.so.1.0`
=> [backport] pruntime: Fix memory leak in logging

crates/phactory/src/contracts/pink.rs, crates/phactory/src/contracts/support.rs, crates/phactory/src/system/mod.rs, crates/pink/capi/src/v1/mod.rs, crates/pink/runner/tests/test_pink_contract.rs, crates/pink/runtime/src/capi/ecall_impl.rs, crates/pink/runtime/src/contract.rs
This change is picked from #1265. Since #1265 would not be released in pruntime v2.0.2, we may want to pick this runtime ABI breaking change out to release in advance.
In pink query, caller can optionally fill an arbitrary number the the arg `deposit` which would be deposited to the caller account before calling the contract so that the runtime can finish the gas estimation even the caller doesn't have enough balance in the cluster to pay the execution.
So there were two call to the pink runtime if non-zero deposit was given:
- `runtime.deposit(amout)`
- `runtime.call(contract_id)`
There is no problem with in memory trie storage. However,  for kvdb backend in #1265 we don't implement an extra cache layer for the DB, the effect of the first call `runtime.deposit()` would be dropped at the …
=> Merge deposit() and contract call() into a single call

crates/pink/runtime/src/runtime.rs, crates/pink/runtime/src/snapshots/pink__runtime__detect_parameter_changes.snap
The default value is 16K. So it couldn't store larger things such as JS code blobs.
=> pink: Enlarge storage value limit to 1MB

Cargo.lock, crates/pink/pink-extension-runtime/src/lib.rs
pruntime crashed on PoC5:
That was because we added some variants in the `enum HttpReqeustError` but the `libpink.so.1.0` is compiled using the old definition which can not decode the new variants. That's what the ABI incompatibility means.
This PR converts the new variants to HttpResponse before passing it the to pink runtime.
=> pruntime: Fix crash due to HTTP ABI incompatibility

.github/actions/build-contracts/action.yml, Cargo.lock, crates/phactory/Cargo.toml, crates/phactory/api/Cargo.toml, crates/phactory/api/src/crypto.rs, crates/phactory/api/src/crypto/eip712.rs, crates/phactory/src/prpc_service.rs, scripts/mm-eip712.html, standalone/prouter/Cargo.lock, standalone/prouter/Cargo.toml, standalone/pruntime/Cargo.lock
This PR adds support for querying to pRuntime with EIP-712 signature which is used in Ethereum wallets.
The current implementation only uses part of the fields of domainSeparator:
```
#[eip712(
name = "Phat Query Certificate",
version = "1",
salt = "phala/phat-contract"
)]
```
the `chainId` is not used. This allow the wallet to sign our messages no matter what active chain is.
A demo front-end script can be found at `scripts/mm-eip712.html` or [here](https://files.kvin.wang:8443/tests/mm-eip712.html).
=> pruntime: Support for query signed in EIP-712

crates/phactory/api/src/crypto/eip712.rs, scripts/mm-eip712.html
This PR adds some descriptive fields to the Metamask signing panel, helping users to understand more clearly what they are signing.
**Preview**
=> eip712: Put more info on the signing panel

crates/phaxt/src/chain_api.rs, standalone/pherry/src/chain_client.rs, standalone/pherry/src/lib.rs
Some proofs were missing when pherry loading proofs with `--load-handover-proof` to a pRuntime with `--safe-mode-level=2`.
I remember we have tested this feature before. Not sure whether it is because of a behavior change in the phala-node.
cc @jasl
=> pherry: Fix missing handover proofs

crates/phactory/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/system/mod.rs, standalone/pruntime/gramine-build/gramine-sgx, standalone/pruntime/gramine-build/pruntime.manifest.template
This PR resolves the pRuntime v2.1 round 2 testing issue.
Changes:
- Configure 2MB gramine stack size for pRuntime
- Handover without touching the `phactory.system`
- Don't load system from checkpoint under `--safe-mode-level=2`
- Print pRuntime exit code in gramine-sgx
=> Safe handover

crates/phactory/src/lib.rs, crates/phala-scheduler/src/request_scheduler.rs
Sorry, the parallelism of `query scheduler` was hard coded to `8`.
This PR make it respect to the `--cores` paramenter as the `sidevm scheduler` did.
=> pruntime: Configurable parallelism for query

Cargo.lock, crates/phactory/Cargo.toml, crates/phactory/src/prpc_service.rs, crates/pink/pink-extension-runtime/Cargo.toml, crates/pink/pink-extension-runtime/src/lib.rs, e2e/contracts/check_system/lib.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/src/ias.rs
This PR addresses the issue of outgoing HTTP requests from pink timing out due to blocking DNS queries executed on a thread pool. The problem is resolved by enabling trust-dns, an asynchronous DNS resolver,  for reqwest.
=> pruntime: Enable trust-dns as resolver for outgoing http

crates/phala-scheduler/src/task_scheduler.rs, crates/sidevm/host-runtime/src/run.rs
The log server stucked at startup(restart) on PoC5.
The reason is that when a SideVM instance exit, the scheduler state machine wasn't reset, and would be reused in later restart.
That would cause an inconsistent state between the scheduler and the VM itself if the SideVM was stopped at a non-Idle state.
This PR fix it by reset the state at exit and each start.
=> pRuntime: Fix sidevm stucks at restart

Cargo.lock, crates/phactory/api/src/contracts.rs, crates/phactory/api/src/lib.rs, crates/phactory/src/contracts/pink.rs, crates/phactory/src/contracts/support/keeper.rs, crates/phactory/src/lib.rs, standalone/phat-poller/Cargo.toml, standalone/phat-poller/src/app.rs, standalone/phat-poller/src/args.rs, standalone/phat-poller/src/query.rs
This PR add support for giving multiple worker URIs with multiple `--dev-worker-uri` and add an argument `--workflow-poll-gap` to set a gap between two workflow polling starts.
for example:
```
./phat-poller run --factory-contract 0x489bb4fa807bbe0f877ed46be8646867a8d16ec58add141977c4bd19b0237091 \
--dev-worker-uri http://localhost:8002 \
--dev-worker-uri http://localhost:8001 \
--workflow-poll-gap 100ms \
--poll-timeout-overall 60s
```
Additionally, an arg `--with-poll-id` is added in order to poll the profile in https://github.com/Phala-Network/phat-bricks/pull/20
=> phat-poller: Support for polling multi workers and delay between flows

e2e/contracts/check_system/Cargo.toml
Or it would cause some problem due to the ink 4.2.0 -> 4.2.1 breaking change.
=> Update phat_js to 0.1.5 for check_system

.github/actions/maximize-disk-space/action.yml, .github/workflows/build-nightly-release.yml, .github/workflows/build.yml
The `easimon/maximize-build-space` solution is complicate and has problem cause the CI randomly fail.
Let's use a simple script to remove the unused stuffs.
Now there is 57G available in `/`:
=> CI: Use our own maximize space script

Cargo.lock, crates/pink/pink-extension-runtime/Cargo.toml, crates/pink/pink-extension-runtime/src/lib.rs, standalone/pruntime/Cargo.lock
When the `tokio::time::timeout` called outside of a tokio runtime context, it complains:
```
panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'
```
The PR fix it by moving it into the Future.
=> pink-runtime: Fix tokio runtime missing in unittest

crates/phactory/src/prpc_service.rs, e2e/src/fullstack.js
This PR add two fields `system_contract` and `logger_contract` to the resposne of `/prpc/PhactoryAPI.GetClusterInfo`. This allows the external tools to be conveniant to query some info from pruntime without touch the chain state.
The field `contracts` is removed as it is a bit heavy and redudant to the API `GetContractInfo`.
=> prpc: Add system contract and so on

crates/pink/runtime/src/contract.rs, crates/pink/runtime/src/runtime/extension.rs, crates/pink/runtime/src/runtime/pallet_pink.rs
As the message in `DispatchError::Other` always be dropped while encoding the error, we'd better define and use our own concrete errors.
=> pink-runtime: Replace DispatchError::Other with concrete errors

crates/phala-node-rpc-ext/src/lib.rs, crates/phala-node-rpc-ext/src/storage_changes.rs, crates/phala-node-rpc-ext/types/src/lib.rs
This PR adds a new phala-node RPC `pha_getStorageChangesWithRoot` which returns storage changes with the corresponding `state root`.
This gives the `headers-cache` ability to validate the storage changes with the block headers.
=> node-rpc: Add pha_getStorageChangesWithRoot

crates/phala-types/src/contract.rs, pallets/phala/src/phat.rs
This PR tries to remove the redunent workers list in ClusterInfo. It also changes the meaning of `ClusterWorkers` which meant Workers that has reported successfully deployed the cluster. As the tx is deterministic, I think the original concept of ClusterWorkers is not necessary. So, this PR changes it to literally indicating workers of the cluster.
The missing workers in old ClusterWorkers would be inserted by the migration.
The reason for keeping `ClusterWorkers` rather than `ClusterInfo::workers` it that it would allow accessing other info in `ClusterInfo` lighter.
@jasl I not sure the migration approch on Khala, please review and comment.
@l00k Could you check whether devPHAse would be affacted by this PR?
@Leechael Could you check whether the SDK and frontend would be affacted?
=> pallet_phat: Remove ClusterInfo::workers

Cargo.lock, crates/phaxt/src/chain_api.rs, crates/phaxt/src/rpc.rs, standalone/headers-cache/Cargo.toml, standalone/headers-cache/src/db.rs, standalone/headers-cache/src/grab.rs, standalone/headers-cache/src/main.rs, standalone/headers-cache/src/web_api.rs, standalone/pherry/src/chain_client.rs, standalone/pherry/src/headers_cache.rs, standalone/pherry/src/lib.rs, standalone/pherry/src/prefetcher.rs
It may encounter a `HeaderHashMismatch` error during block synchronization with headers-cache if it is configured to automatically fetch blocks from the node. This issue may arise due to the node temporarily returning incorrect block data. 
This pull request adds:
-  Automated checking for to the header hash chain and re-fetching the header data from the node in case of a hash mismatch.
- Additionally, an external web API is exposed at `/check` to manually invoke these checks, for example:
```bash
#!/bin/bash
FROM=15000000
TO=17353475
BATCH=100000
CHAIN=relay # or para or state
for (( i=$FROM; i<=$TO; i+=$BATCH )); do
NEXT=$((i + BATCH - 1))
if [ $NEXT -gt $TO ]; then
NEXT=$TO
fi
curl "localhost:8003/check?chain=$CHAIN&from=$i&to=$NEXT"
echo
done
```
The storage changes could not be …
=> headers-cache: Check headers hash chain

pallets/phala/src/compute/base_pool.rs, pallets/phala/src/compute/vault.rs, pallets/phala/src/mock.rs, pallets/phala/src/snapshots/phala_pallets__test__vault_force_withdraw_after_3x_grace_period.snap, pallets/phala/src/snapshots/phala_pallets__test__vault_partial_force_withdraw-2.snap, pallets/phala/src/snapshots/phala_pallets__test__vault_partial_force_withdraw.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw1.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw2.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw3.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw4.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw5.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw6.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw7.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw8.snap, pallets/phala/src/snapshots/phala_pallets__test__withdraw9.snap, pallets/phala/src/test.rs
A few security and accounting improvements:
- Allow a vault force withdraw requests to be partially filled whenever there's available stake in stake pool by calling `check_and_maybe_force_withdraw`
- Trigger fall safe vault force withdraw when there's a request with 3x grace period (21 days)
- Trigger vault owner reward settle at the beginning of `contribute()` and `withdraw()`
- Add precise burnt shares to the `Withdrawal` event
- Add withdrawing NFT id to the `WithdrawalQueued` event
=> StakePool and Vault improvements

frontend/packages/sdk/package.json, frontend/packages/sdk/pbconfig.json, frontend/packages/sdk/src/OnChainRegistry.ts, frontend/packages/sdk/src/pruntime/proto/index.d.ts, frontend/packages/sdk/src/pruntime/proto/index.js
In the current version, we automatically connect to the first registered worker from `phalaRegistry.endpoints`. However, this may not be available because this API only stores the endpoint URL for each worker. Instead, we should use `phalaPhatContracts.clusterWorkers` to obtain the full list of available workers. This PR proposes to change the way health workers are picked up. It should not impact the auto-connect logic:
```typescript
const apiPromise = await ApiPromise.create(options({
provider: new WsProvider(ws),
noInitWarn: true
}))
const registry = await OnChainRegistry.create(apiPromise)
```
However, we are also introducing a new struct called `WorkerInfo` and redesign the API for connecting to a specified worker in a clearer manner. For example, we connect to the random worker in …
=> Redesign the API that connect to specified worker

pallets/phala/src/phat.rs, standalone/runtime/src/lib.rs
This  PR fixes a bug in the pallet-phat migration code where removed workers weren't being deleted from `Cluster::workers`, leading to their erroneous re-addition to `ClusterWorkers` during migration.
The PR excludes these removed workers in the migration process. Additionally, a new sudo API, `cleanup_removed_workers`, is added for cleaning up any workers mistakenly added due to this bug.
=> pallet-phat: Fix phat migration error

Cargo.lock, crates/pink-drivers/log_server/Cargo.toml, crates/pink-drivers/sidevm_deployer/Cargo.toml, crates/pink-drivers/system/Cargo.toml, crates/pink-drivers/tokenomic/Cargo.toml, crates/pink-libs/s3/Cargo.toml, crates/pink-libs/subrpc/Cargo.toml, crates/pink-libs/utils/Cargo.toml, crates/pink/pink-extension-runtime/Cargo.toml, crates/pink/pink-extension/Cargo.toml, crates/pink/pink-extension/README.md, crates/pink/pink-extension/src/lib.rs, e2e/contracts/check_system/Cargo.toml, e2e/contracts/check_system/lib.rs, standalone/pruntime/Cargo.lock
I've made a [drink](https://github.com/inkdevhub/drink) runtime for pink [here](https://github.com/Phala-Network/drink-pink-runtime).
This PR show an example for how to do quasi-E2E test using it, and makes some changes to pink-extention to make the framework work.
There are 2 issue I encountered (Both has been resolved):
=> Example for testing with drink

crates/phactory/src/prpc_service.rs
It took me a lot of time to debug the `bad justifacation` error without this log.
=> pruntime: Show authority set change in log

Cargo.lock, standalone/prb/Cargo.toml, standalone/prb/src/datasource.rs
Some prbs may manage hundreds or thousands of workers. For each worker, prb will check the headers every 3 seconds. Since the block producing every 12 seconds, 3/4 of the checks get nothing.
In the old implemention, for None, the cache layer will just invalidate the cache. It causes node connection issue since every worker in the prb connect to node every 3 seconds, even just few milliseconds ago another worker checked there is no new header.
Instead of no cache, we need to cache None but for short expiry for reducing the unnecessary node connection.
=> prb: add per-entry expiration for None items instead of no cache

crates/phactory/api/src/proto_generated/mod.rs, crates/phactory/pal/src/lib.rs, crates/phactory/src/prpc_service.rs, crates/sgx-attestation/src/dcap.rs, standalone/pherry/src/lib.rs, standalone/prb/src/cli.rs, standalone/prb/src/datasource.rs, standalone/prb/src/lifecycle.rs, standalone/prb/src/wm.rs, standalone/prb/src/worker.rs, standalone/pruntime/src/pal_gramine.rs
This PR mainly adds support for Dcap attestation processing in prb.
with two additional changes:
1. fixed a bug in pherry args that doesn't accept `--attestation-provider=dcap`
2. added supported_attestation_methods in get_info so that prb can init pruntime according to it.
=> prb: Support for Dcap

Cargo.lock, crates/phactory/Cargo.toml, crates/phactory/src/lib.rs, crates/this-crate/Cargo.toml, crates/this-crate/src/lib.rs, standalone/pruntime/Cargo.lock, standalone/pruntime/Cargo.toml, standalone/pruntime/src/main.rs
We never want older version of pruntime to load checkpoints saved from newer version of pruntime, as it could lead to security risks.
We currently save a version number in the checkpoint and verify its compatibility. However, this version number requires manual updating in the source code, which can be easily overlooked. 
This PR links the storage version number to phactory's crate version number and synchronizes the versions of phactory and pruntime.
=> pruntime: Reject old version of checkpoint

frontend/packages/sdk/src/contracts/PinkLoggerContract.ts, frontend/packages/sdk/src/factory_functions.ts, frontend/packages/sdk/src/utils/snakeToPascalCase.ts, frontend/packages/sdk/tests/contracts/PinkLoggerContract.test.ts, frontend/packages/sdk/tests/utils/snakeToPascalCase.test.ts
This PR intent to added follow up features to `PinkLoggerContractPromise`:
- Specify the type filter to only return messages that match the specified type. The available types are: `Log`, `Event`, `MessageOutput`, `QueryIn`, and `TooLarge`.
- If you have selected the "Event" filter type, you can also add an optional topic filter. The topic filter should be in a human-readable format like "System::getLog".
- Use the custom Abi for decoding events.
[The `tail.js` script in the cookbook](https://github.com/Leechael/phat-contract-sdk-cookbook/blob/main/tail.js) can be enabled to have follow features:
1. Only show latest contract event:
```bash
node tail.js --type Event
```
2. Only show latest contract event from specified `contractId`:
```bash
node tail.js <contract_id> --type Event
```
3. …
=> Improved: Logger & Contract Event decoding

crates/sgx-attestation/src/ias.rs
IAS version 4 marks advisoryURL and advisory is optional.
I think give a default value on deserializing is enough, follows
https://serde.rs/attr-default.html#default-value-for-a-field
=> Prevent crash if no advisoryURL or advisoryIDs

crates/sgx-attestation/src/ias.rs
This resolve the issue `InvalidReport` in `register_worker`.
=> [Backport][chain v0.1.26] Prevent crash if no advisoryURL or advisoryIDs

crates/phactory/src/contracts/support.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/snapshots/phactory__show_type_changes_that_affect_the_checkpoint.snap, crates/phactory/src/system/mod.rs
In the previous implementation, contract code_hashes were stored in memory. Therefore, if a contract upgraded itself using `set_code_hash`, the recorded code_hash wouldn't update. This led to incorrect code_hash returns in subsequent GetContractInfo calls. 
This PR addresses this issue by removing the in-memory storage of code_hashes and instead querying them from storage.
=> pruntime: Fix incorrect code_hash in prpc::GetContractInfo

Cargo.lock, crates/sidevm/sidevm/Cargo.toml, crates/sidevm/sidevm/src/net.rs
The small chunk size limit make the net io poor performance. Let the caller decide the chunk size.
=> sidevm: Remove the 512 bytes chunk size limit

Cargo.lock, crates/sidevm/host-runtime/Cargo.toml, crates/sidevm/host-runtime/src/env.rs, crates/sidevm/host/Cargo.lock, standalone/pruntime/Cargo.lock
By default, tokio uses the blocking DNS resovler from libc and run them in a thread pool.
That would cause problem such as run out of thread-pool in some poor network situation.
So, let's use trust-dns as the resolver.
=> sidevm: Use trust-dns as DNS resolver

Cargo.lock, crates/phactory/api/Cargo.toml, crates/phactory/src/light_validation/mod.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/storage.rs, standalone/pherry/src/lib.rs, standalone/pruntime/Cargo.lock, standalone/replay/src/replay_gk.rs
According to the upstream change [here](https://github.com/paritytech/polkadot-sdk/pull/2181/files#diff-d87d7e51ef525dc88a419ecbcf83d5a69afb3dd91aec05c99e81c46ef5368ecaR346).
By the way, dropped the compatibility of `PhalaMa::OutboundMessagesV2` in pruntime as the on-chain implementation #828 was dropped.
=> Read the validator set from `Grandpa::Authorities` as a fallback

crates/phactory/src/light_validation/mod.rs
pRuntime recently encountered "invalid ancestry proof"。 After digged into the log, it turned out that when pRuntime get invalid validator set proofs, it would abort with an error but still update the last header.
This PR fixes it by move the updating statement after the proof checking finished.
=> pruntime: Fix possible mis-update last_header on error

pallets/phala/src/utils/constants.rs
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteVerification/QVL/Src/AttestationLibrary/src/Verifiers/QuoteVerifier.cpp#L186-L231
=> Correct DCAP constants

crates/pink/runtime/src/capi/ecall_impl.rs
As the execution env of phat contract is faster than the on-chain version.
=> pink runtime: Increase gas limit to 5x

e2e/src/fullstack.js, standalone/node/src/chain_spec.rs, standalone/node/src/cli.rs, standalone/node/src/command.rs, standalone/node/src/service.rs
The hardcoded `gossip_duration=333ms` caused the phala-node block finalizing interval to be at least 1s. Therefore, it remained slow even when we set the block interval to 100ms in e2e.
This PR introduces configurability to the gossip_duration, allowing for more flexibility.
=> phala-node: Configurable gossip duration.

Cargo.lock, Makefile, standalone/pherry/Cargo.toml, standalone/pherry/src/authority.rs, standalone/pherry/src/headers_cache.rs, standalone/pherry/src/lib.rs, standalone/pherry/src/types.rs, standalone/prb/src/datasource.rs
This PR adds the below improvements to `pherry` and `headers-cache`:
- Verifying justifications
- Checking the authority set by comparing the data from RPC to the one extracted from the trie.
This would reduce the chance of data corruption in headers-cache.
=> pherry: Verify justification and authority set

frontend/packages/sdk/package.json, frontend/packages/sdk/src/OnChainRegistry.ts, frontend/packages/sdk/src/contracts/PinkBlueprint.ts, frontend/packages/sdk/src/contracts/PinkCode.ts, frontend/packages/sdk/src/contracts/PinkContract.ts, frontend/packages/sdk/src/contracts/PinkLoggerContract.ts, frontend/packages/sdk/src/factory_functions.ts, frontend/packages/sdk/src/index.ts, frontend/packages/sdk/src/providers/EvmAccountMappingProvider.ts, frontend/packages/sdk/src/providers/KeyringPairProvider.ts, frontend/packages/sdk/src/providers/UIKeyringProvider.ts, frontend/packages/sdk/src/providers/types.ts, frontend/packages/sdk/src/pruntime/certificate.ts, frontend/packages/sdk/src/types.ts, frontend/packages/sdk/tests/pruntime/certificate.test.ts, frontend/packages/sdk/yarn.lock
This PR propose for add a simple layer call `provider`, holding the signer & transport implementation so we can,
1. Implement additional singer and transport functionality without introducing any breaking changes to ApiPromise.
2. Better dependency injection in future contract class design.
The new API was introduced without breaking compatibility with the original API.
The `provider` refers to one of the follows:
```ts
import { EvmAccountMappingProvider, KeyringPairProvider, UIKeyringProvider } from '@phala/sdk'
//
// Using KeyringPairProvider for node.js based project.
//
const provider = await KeyringPairProvider.create(apiPromise, suri)
//
// Using UIKeyringProvider in browser, you need collect which wallet extension & account to use before continue.
//
const appName = 'My dApp'
const …
```
=> JS-SDK: Provider & Proxy based PinkContractPromise API

.github/workflows/build.yml, Cargo.lock, crates/phactory/api/Cargo.toml, crates/phactory/api/src/crypto.rs, crates/phactory/api/src/crypto/eip712.rs, crates/phactory/src/prpc_service.rs, e2e/src/fullstack.js, standalone/pruntime/Cargo.lock
As we are likely going to release a new 2.1.x patch version for the Authorities issue, let includes this fix as well.
=> [backport-to-v2.1.x] pruntime: Address mapping from H160 in query

.gitmodules, crates/phactory/api/proto/prpc.proto, crates/phactory/api/proto/pruntime_rpc.proto
We split the proto files to the external repo long time ago for prb v2 and js-sdk. Now that both of them are moved back to this repo, the proto files are no longer needed to be in a separate repository. Let's move them back for better PR review and conflict resolution experience.
=> Move the prpc proto files back from external repo

crates/pink/chain-extension/src/lib.rs, crates/pink/pink/src/chain_extension/http_request.rs, crates/pink/pink/tests/snapshots/test_chain_extensions__dump_type_info.snap
This fixes the audit report https://github.com/code-423n4/2024-03-phala-network-findings/issues/46
=> pink: Limit number of http headers to 256

Cargo.lock, crates/rustfmt-snippet/Cargo.toml, crates/rustfmt-snippet/src/lib.rs
Use stdin instead as rustfmt supports it now.
=> Remove tempfile usage in rustfmt-snippet

crates/phactory/src/contracts/support/keeper.rs, crates/phactory/src/prpc_service.rs, crates/phactory/src/system/gk.rs
This PR intends to solve the stack overflow issue in pRuntime by boxing the large values in OrdMap. 
In the previous implementation, we utilize `OrdMap<H256, Contract>` to store the contract info, where `sizeof::<Contract> == 1064`. Even though the size of Contract is approximately 1k, the `OrdMap::insert` demanded an over 8MB stack in certain scenarios. (Not sure why!)
After being boxed, it works fine when 200,000 contracts are deployed, with a 300k stack size.
=> pruntime: Box large value in OrdMap

Cargo.lock, crates/phactory/src/prpc_service.rs, standalone/pruntime/src/runtime.rs
It will return an error if the runtime is syncing chain state while an incoming HTTP request to SideVM arrives. This behavior is unnecessary. This PR fixes the issue.
=> pruntime: Allow HTTP proxy to sidevm when syncing chain state

crates/pink-libs/subrpc/Cargo.toml, crates/pink-libs/subrpc/src/lib.rs
Add `subprc::get_finalized_head` method
=> Add a method to get the latest hash of the finalized header

.github/actions/install_toolchain/action.yml, Cargo.lock, dockerfile.d/05_rust.sh, pallets/phala/src/compute/vault.rs, pallets/phala/src/snapshots/phala_pallets__test__vault_force_withdraw_with_dust_investment.snap, pallets/phala/src/test.rs, rust-toolchain.toml
- Skip stake pools with missing/dust NFTs during force withdrawal
- Clean up invest_pools list by removing pools with no valid investment
- Add test case to verify dust investment handling
This fixes a potential panic when a vault tries to force withdraw from a stake pool where its NFT was already burned due to dust shares.
=> Fix vault force withdraw bug with burnt stake pool share

frontend/apps/prb3-monitor/src/components/Nav.js, frontend/apps/prb3-monitor/src/pages/[wm]/inv/po.js, frontend/apps/prb3-monitor/src/pages/[wm]/inv/pool.js, frontend/apps/prb3-monitor/src/pages/[wm]/inv/worker.js, frontend/apps/prb3-monitor/src/pages/[wm]/status/tx.js, frontend/apps/prb3-monitor/src/pages/[wm]/status/worker.js, frontend/apps/prb3-monitor/src/pages/api/p/[...slug].js, frontend/apps/prb3-monitor/src/state.js
Adds navigation through different WMs via url. WM key is used as first part in URL.
In case you manage multiple different WMs it is easier to create bookmarks and open multiple windows with different WMs at once.
With previous implementation (local storage) change WM in one tab made all other tabs to switch WM.
My docker image for tests: https://hub.docker.com/r/l00ky/prb3-monitor
=> Add WM navigation through url

crates/phactory/api/proto/pruntime_rpc.proto, crates/phactory/src/prpc_service.rs
This PR adds a blocknum in the query response so that the front end can make sure the returned data is based on the correct block state.
Note: All RPC responses are already signed by the worker identity key.
=> pruntime: Adds blocknum in query response
